### ISSUE TITLE
When -H 0.0.0.0 is used, a nonsensical livereload.js script tag is added

### ISSUE THREAD

**Issue by xentac** [aumayr/fava#108]
I use beancount-web within a docker container, so the local IP doesn't make any sense anyway.

-H 0.0.0.0 leads to <script src="http://0.0.0.0:5000/livereload.js"></script>

**Comment by xentac** [comment]
That was supposed to be a http://0.0.0.0:5000/livereload.js script tag...

**Comment by corani** [comment]
This looks like an issue that has already been fixed in livereload: https://github.com/lepture/python-livereload/commit/2ca26a04b8c235d81171684208a7f4cbe5c5e78d

**Comment by aumayr** [comment]
@xentac Does this answer your question?

**Comment by corani** [comment]
@lepture is it correct that https://github.com/lepture/python-livereload/commit/2ca26a04b8c235d81171684208a7f4cbe5c5e78d (fix for using host: 0.0.0.0) isn't in the pypi version (2.4.0) yet? If so, any chance of pushing a new version?

**Comment by xentac** [comment]
The current version is slightly better, but it still hardcodes a port (I'm using it within a docker container and redirecting the port anyway).  It seems like the livereload library itself could just use an absolute path without specifying the hostname and things would be better.

But given what it does, I think I'd prefer a flag to just not enable livereload.  It's not very onerous for me to hit reload after I make a change...

**Comment by aumayr** [comment]
@xentac The `--debug`-flag does start `beancount-web` without livereload enabled (but with debugging-output if something goes wrong).

**Comment by lepture** [comment]
@corani 2.4.1 was released.

**Comment by corani** [comment]
@xentac let me know if the latest update fixes the issue for you.

**Comment by xentac** [comment]
As I mentioned before, this one does give a better hostname, but it still doesn't work if I use a reverse proxy or a different internal docker port than the exposed external one.

It really seems like https://github.com/lepture/python-livereload/blob/master/livereload/server.py#L224 could just be converted to "/livereload.js" to get the same effect without any problems with hostnames or ports.  I don't understand why the hostname is necessary in that part.

**Comment by corani** [comment]
Ah, I see what you mean. The issue is that they're still hardcoding the port, while that should be gotten through JavaScript as well. Or, as you suggest, remove the host and port altogether. In that case they needn't even use the JavaScript workaround.

Could you file a bug against LiveReload?

**Comment by xentac** [comment]
Filed: https://github.com/lepture/python-livereload/issues/132

**Comment by aumayr** [comment]
@xentac Can I close this issue?

**Comment by xentac** [comment]
Yeah, we can close it.
