### ISSUE TITLE
Installing is broken

### ISSUE THREAD

**Issue by aumayr** [aumayr/fava#127]
Things about the installation to fix:

- [ ] PyPI does not list `beancount-fava` in it's search results, so `pip3 install beancount-fava` does not work
- [x] `beancount` does miss `python-dateutil` and `ply` from it's requirements, so these two have to be installed manually
- [x] `gen/style.css` and the `gen/*.js`-files are missing from the release .zip-s, so even when installed from source it does not work

**Comment by aumayr** [comment]
@yagebu What is the best workfow for the last point (`gen/..`)?

**Comment by yagebu** [comment]
> PyPI does not list beancount-fava in it's search results, so pip3 install beancount-fava does not work

From looking at PyPI's bug tracker, it seems that search is somewhat broken, or the search index doesn't get updated often. Let's just hope it get's fixed quickly...

> beancount does miss python-dateutil and ply from it's requirements, so these two have to be installed manually

@blais Is there anything blocking [beancount Issue 72](https://bitbucket.org/blais/beancount/issues/72/consider-installing-with-setuptools-again)? This would greatly simplify installation of `beancount` and `fava`. @aumayr as a workaround, we could just include them in our dependencies as long as `beancount` doesn't...

> gen/style.css and the gen/*.js-files are missing from the release .zip-s, so even when installed from source it does not work

If I create a source distribution (with `python3 setup.py sdist [--format=zip]`), the generated files are included. How did you build the release?

**Comment by aumayr** [comment]
I fixed some of the things mentioned above: 

- correct files are included/excluded
- description and keywords get added to PyPI
- version number is parsed from `fava/__init__.py` instead of hardcoding it twice
- `python-dateutil` and `ply` added to requirements to fix [beancount Issue 72](https://bitbucket.org/blais/beancount/issues/72/consider-installing-with-setuptools-again)

I testet it on the PyPI test-server and it worked as expected. I will push a new version to PyPI (0.2.2) to test if it will show up in the search results now.

**Comment by aumayr** [comment]
What is still missing is the following:

- `beancount` does not install well, because the PyPI entry is too old (2014-09-07) and installing it via the URL to the bitbucket-repo does fail (and has to be invoked as `pip install beancount-fava --process-dependency-links' to enable the URL-fetching-feature at all).

- `beancount-fava` does not show up in the search results on PyPI. 

The current version is broken, not only because of `beancount`, but there is a bug in `setup.py` which I fixed in e9abd56, but haven't created a new version just for that. The installation of `beancount` as a dependency has to be fixed before I create a new version.

**Comment by blais** [comment]
I applied the changes from issue #72, in a new branch called "setuptools_issue72".
My unit tests appear to work for both cases, where setuptools is present or absent.
I'm also able to install with pip3.
Can you please test this and see if this job the job for you?

I'll also mark a 2.0b4 version and refresh the PyPI entry.

If you need anything else let me know.

**Comment by blais** [comment]
Actually, in order to bake a new release I think I probably need to merge to default. I'll do that, it appears to work.

**Comment by blais** [comment]
New release available here: https://pypi.python.org/pypi/beancount/2.0b4

**Comment by blais** [comment]
This still doesn't work. Setuptools is stupid: if I don't list the header files, they're not included, if I use "headers", it silently ignores the option, does not fail, but fails to include the files; if I list them in "sources", it refuses to build saying it doesn't recognize the file types, if I include them as extra_objects, it does include them in the output but it fails to build. Setuptools is SHYTE.

I'll have to address this later. I'm on vacation.

**Comment by blais** [comment]
I have a workaround baked as 2.0b6. This should work with pip3 and build it locally.

**Comment by yagebu** [comment]
> I have a workaround baked as 2.0b6. This should work with pip3 and build it locally.

Works for me :+1:
