### ISSUE TITLE
Balance summaries (balance sheet, trial balance) are based on lot price, not current price

### ISSUE THREAD

**Issue by xentac** [aumayr/fava#129]
I would have expected that the prices at the end of the period would be used in the conversion instead of price when I purchased the commodity.  This way makes it much harder to figure out the state of my accounts.

Is there a reason to do it this way?

I can create an example file to show what I'm talking about if necessary.

**Comment by yagebu** [comment]
From an accounting standpoint, the current behaviour is the correct thing to do. The balance sheet should display the "book value" of your assets (and liabilities), that is the original cost of the asset (minus depreciation possibly). Wikipedia has [more](https://en.wikipedia.org/wiki/Book_value) on the meaning of book value and maybe the [Beancount trading doc](https://docs.google.com/document/d/1WjARst_cSxNE-Lq6JnJ5CC41T3WndEsiMw4d46r2694/edit#heading=h.5o43cxhng7b7) gives some further insight.

I agree with you that it would be useful to have a report that reports the account balances based on the market values (and displays charts based on the market value), but it should be separate.

**Comment by aumayr** [comment]
Can I close this, @xentac?

> I agree with you that it would be useful to have a report that reports the account balances based on the market values (and displays charts based on the market value), but it should be separate.

@yagebu Any ambitions to follow up on that with a PR? If yes: Please create a new ticket for it. If no, just discard this comment :-)

**Comment by yagebu** [comment]
> Any ambitions to follow up on that with a PR? If yes: Please create a new ticket for it. If no, just discard this comment :-)

Will do. Although I haven't really thought about how to best do this, so if anyone else is keen or has some ideas, feel free to work on it.

**Comment by xentac** [comment]
Looking at the trading doc, it pointed me at the unrealized_gains plugin.  This is good enough for my purposes right now.  I'm imagining a modification to the plugin to be able to compute unrealized gains every month (or maybe even every price db entry).

**Comment by aumayr** [comment]
@xentac Please have a look at the new views in the Holdings report
