### ISSUE TITLE
Show query directives (titles) as submenus to "Query" view in sidebar

### ISSUE THREAD

**Issue by aumayr** [aumayr/fava#131]

**Comment by corani** [comment]
I can take a shot at this. Do you have something like this in mind:

- Custom Queries
  - Query 1
  - Query 2
  - Query 3

(Maybe limit the number of queries to default 5, with a configuration option for a different number?)

**Comment by aumayr** [comment]
@corani Yes, exactly that! 5 as a limit sounds reasonable, with the date as the basis for sorting.
