### ISSUE TITLE
Commodities only forward pairs are shown

### ISSUE THREAD

**Issue by corani** [aumayr/fava#139]
I only have currencies as commodities, and found that the inverse rates weren't shown under commodities due to:

https://github.com/aumayr/fava/blob/master/fava/api/__init__.py#L478

While this would make sense for stocks, for currencies you usually want to see the inverse as well.

**Comment by corani** [comment]
As a solution, I have a meta-tag `asset-class: "Cash"` on all my currency commodities, maybe this could be used to determine for which commodities the inverse should be shown?

**Comment by yagebu** [comment]
If we add something to distinguish between currencies and other commodities, it would be nice if it worked automatically without having to add any metadata. I don't put any `commodity` directives for currencies anyway.

How about using the following heuristic: If the commodity name has three letters or less (as all the ISO 4217 currency codes do), treat it like a curreny.

**Comment by corani** [comment]
It's not ideal, since there certainly are three or less letter stocks, but it would work for me.

Some other ideas:
- only do this for `operating_currency`
- use a (hardcoded) list of currency codes
- configuration option

**Comment by aumayr** [comment]
> How about using the following heuristic: If the commodity name has three letters or less (as all the ISO 4217 currency codes do), treat it like a currency.

This calls for a default of "disabled" and a configuration option to enable it, because it would confuse users if they do not know about this convention. So my vote is for "configuration over convention" ;-)

**Comment by yagebu** [comment]
If possible, I would refrain from adding another option and the following seems to be the best suggestion: 

> - only do this for operating_currency

**Comment by aumayr** [comment]
@yagebu Is the formatting of the numbers in the following screenshot accidental? (CHF/EUR is the calculated one)

![screenshot](https://cloud.githubusercontent.com/assets/5135450/13790618/a3e248c0-eae9-11e5-90d0-5609fa48bc9e.png)

**Comment by yagebu** [comment]
@aumayr: turns out that `format_currency` wasn't used. It is now.
