### ISSUE TITLE
Net worth disagrees with bean-report

### ISSUE THREAD

**Issue by xentac** [aumayr/fava#141]
When I run bean-report networth I get different numbers in my two currencies than from fava.  The bean-report numbers are higher and closer to what I was seeing about a month ago with fava.  My guess is something changed.

**Comment by aumayr** [comment]
This is not good. Can you provide a sample file where this is happening?

(Ref #126)

**Comment by xentac** [comment]
I don't know that I can do this in the next week or so... I'm about to go on vacation.  Otherwise I would have given more information and done some debugging ;)

**Comment by happyalu** [comment]
I just saw this too. I couldn't quickly come up with a minimal example of this bug. But it might be related to cost/prices.

I have two currencies (INR and USD), and fava matches with beancount's report exactly on INR. On USD, it's way off. It's reporting less than half of what beancount reports.

**Comment by yagebu** [comment]
The calculation of the net worth is the last place where we do basic arithmetic by hand, which we shouldn't do and which might lead to this bug. I'll rewrite the code to use `beancount`'s functions, that should hopefully fix it.

**Comment by yagebu** [comment]
Can you try my branch [net-worth](https://github.com/yagebu/fava/tree/net-worth) to see if that changes anything?

**Comment by xentac** [comment]
Can confirm this is fixed.
