### ISSUE TITLE
"Red Circle" for valid balance checks

### ISSUE THREAD

**Issue by happyalu** [aumayr/fava#143]
I'm seeing red circle for all balance checks in the "statistics" page. If I click the account and look at the entries, the balance transaction appears in green. 

It was working very well with an early version of beancount-web, I just updated to the latest pip installation yesterday :)

**Comment by aumayr** [comment]
@happyalu Can you provide a test beancount file where this happens? Maybe with just the last few transactions and the balance check (anonymized) for the account where this happens.

**Comment by aumayr** [comment]
Ref #35

**Comment by happyalu** [comment]
option "operating_currency" "INR"

2014-12-01 open Assets:Cash
2014-12-02 open Assets:Savings

2014-12-24 * "" | "Cash Deposit"
  Assets:Cash                                                    -1000.00 INR
  Assets:Savings

2015-02-02 * "" | "Cash Deposit"
  Assets:Cash                                                    -1000.00 INR
  Assets:Savings

2015-02-03 balance Assets:Savings                                 2000.00 INR
![x](https://cloud.githubusercontent.com/assets/231523/13208751/f4f8bc30-d941-11e5-9fe5-612713c611ad.png)

**Comment by yagebu** [comment]
Did you have any filters active when you took the screenshot? It seems that currently only the filtered entries are considered for the up-to-date indicator (which is a bug imho).

**Comment by aumayr** [comment]
The "specification" for the up-to-date-indicators is still very basic, and a discussion of the shortcomings and suggestions how to fix them is in #35 

>  It seems that currently only the filtered entries are considered for the up-to-date indicator (which is a bug imho).

It definitely is. This feature still needs some work…

**Comment by happyalu** [comment]
I seem to get a red circle with no filters as well as say, the YTD or "This Month" filter.

**Comment by aumayr** [comment]
@happyalu This should be fixed in `master`, but is obeying filters still. Until this is changed to ignore active filters (and implement #35) it may still be a few days out, but as far as this bug is concerned it should be fixed. 

Can you confirm that it is working now?

**Comment by happyalu** [comment]
Works. Thanks!
