### ISSUE TITLE
Fava website

### ISSUE THREAD

**Issue by aumayr** [aumayr/fava#150]
Create a basic website (gh-pages) with screenshots and so forth. 

Could mirror/include the content of the Help pages (#149)

**Comment by yagebu** [comment]
The website is now live at https://aumayr.github.io/fava/.

**Comment by aumayr** [comment]
Looks very good! Thanks! 

I will add a logo to the top of the left sidebar in the next days.

**Comment by aumayr** [comment]
@yagebu I added a logo and updated the page: https://aumayr.github.io/fava/

**Comment by yagebu** [comment]
:+1:
