### ISSUE TITLE
Interactive "console" to run bean-* commands

### ISSUE THREAD

**Issue by aumayr** [aumayr/fava#151]
It may be feasable to run bean-* commands inside fava/the browser - anyone interested in this?

**Comment by yagebu** [comment]
I don't think it's really worth the effort. For features that we want to provide we should integrate custom reports. Including a shell doesn't really offer anything the user couldn't do in the terminal. And unlike the Query page we can't really improve the output and link accounts for example.

**Comment by aumayr** [comment]
I agree. This was just a quick idea, and not to forget it I opened this issue. Will close as "wontfix".
