### ISSUE TITLE
No autoreload for documents

### ISSUE THREAD

**Issue by corani** [aumayr/fava#156]
With the `beancount` option:

```
option "documents" "/path/to/documents"
```

you can add a (root) folder for documents. When you place documents there, they'll be automatically included in your journal.

Currently, this folder isn't monitored, so you need to manually restart the application (or force a reload by saving a source file) before documents show up.

**Comment by aumayr** [comment]
@corani Fixed in #467b5be. Please try if this is working for you.

**Comment by corani** [comment]
Unfortunately, no. The documents folders need to be added recursively, and any folders created while running, need to be added as well.

**Comment by aumayr** [comment]
I just tested (Mac OS 10.11.3) and it does work recursively for me. On which system are you?

**Comment by corani** [comment]
Ubuntu 14.04

I'll try to do some more testing later today.

On Tue, Feb 23, 2016 at 5:44 PM, aumayr <notifications@github.com> wrote:

> Reopened #156 <https://github.com/aumayr/fava/issues/156>.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/aumayr/fava/issues/156#event-561310590>.
>



-- 
Best regards,
Daniël Bos


Your government is reading your email. Slow them down with encryption.

My public key: http://goo.gl/gms497 (4096 bit RSA, id EF2D5D91)
Fingerprint  : D8D0 9FBE F075 F709 7B52  2F73 326C 2123 EF2D 5D91

**Comment by aumayr** [comment]
OK, please let me know what you found out. I'll leave the issue open for now.

**Comment by corani** [comment]
It looks like it indeed works recursively. I see the `Reload 1 waiters` log message and the page reloads. However, the new document doesn't show up until I manually restart the application.

Additionally, I noticed two things while saving the config file:
- When I remove the `theme = alternative` option, it doesn't revert back to `default`. If I put in an explicit `theme = default`, it works file, but apparently it doesn't clear the previous user-config settings when reloading.
- When saving, I get the following exception:

```
[E 160223 21:42:15 ioloop:629] Exception in callback <bound method LiveReloadHandler.poll_tasks of <class 'livereload.handlers.LiveReloadHandler'>>
    Traceback (most recent call last):
      File "/home/daniel/.pyenv/versions/3.5.1/lib/python3.5/site-packages/tornado/ioloop.py", line 1039, in _run
        return self.callback()
      File "/home/daniel/.pyenv/versions/3.5.1/lib/python3.5/site-packages/livereload-2.4.1-py3.5.egg/livereload/handlers.py", line 66, in poll_tasks
        filepath, delay = cls.watcher.examine()
      File "/home/daniel/.pyenv/versions/3.5.1/lib/python3.5/site-packages/livereload-2.4.1-py3.5.egg/livereload/watcher.py", line 73, in examine
        func and func()
      File "/home/daniel/.pyenv/versions/3.5.1/lib/python3.5/site-packages/beancount_fava-0.2.3-py3.5.egg/fava/cli.py", line 106, in <lambda>
        server.watch(settings_path, lambda: reload_settings(server))
    TypeError: reload_settings() missing 1 required positional argument: 'settings_path'
```

**Comment by aumayr** [comment]
> - When saving, I get the following exception:
> 
> ```
> ...
>       File "xxx/3.5.1/lib/python3.5/site-packages/beancount_fava-0.2.3-py3.5.egg/fava/cli.py", line 106, in <lambda>
>         server.watch(settings_path, lambda: reload_settings(server))
>     TypeError: reload_settings() missing 1 required positional argument: 'settings_path'
> ```
> 

Fixed in 61c72f0

**Comment by aumayr** [comment]
>  - When I remove the theme = alternative option, it doesn't revert back to default. If I put in an explicit theme = default, it works file, but apparently it doesn't clear the previous user-config settings when reloading.

Fixed in 840a308

**Comment by aumayr** [comment]
> It looks like it indeed works recursively. I see the Reload 1 waiters log message and the page reloads. However, the new document doesn't show up until I manually restart the application.

This is still open. I have to set up a test VM and everything, so this could take a while...

**Comment by corani** [comment]
61c72f0 and 840a308 confirmed fixed.

**Comment by aumayr** [comment]
👍

**Comment by corani** [comment]
This is still open. After adding a document (directly in the folder, or uploading through fava), I get the following log message:

```
[I 160228 11:14:48 handlers:92] Reload 1 waiters:
```

The page reloads, but the new document doesn't show up.

**Comment by yagebu** [comment]
This is a beancount issue, as the pickle cache prevents the documents folder from being rescanned.

Ref beancount [Issue 122](https://bitbucket.org/blais/beancount/issues/122/pickle-cache-prevents-document-folder-from)

**Comment by aumayr** [comment]
Any update on this?

**Comment by yagebu** [comment]
Not as far as I can see. If someone wants to work on this, beancount's [#123](https://bitbucket.org/blais/beancount/issues/123/option-to-disable-pickle-cache) would be the way forward. Shouldn't be too hard to implement (but for me it's quite a low priority).

**Comment by yagebu** [comment]
This was actually just a one-line change...

Using an internal function is not ideal of course, but in this case it's worth it. We're following beancount's development close enough anyway.
