### ISSUE TITLE
Upload documents

### ISSUE THREAD

**Issue by corani** [aumayr/fava#157]
I'd like the ability to upload documents by dropping them on an `account` page. For example, when I drop a document on the `Liabilities:Bank:Credit-Card` account page, it should store the document in the `document` folder, under `Liabilities/Bank/Credit-Card/<date>.document-name.ext` Probably it should ask to enter a date, if the document doesn't start with one, so you don't need to rename the documents in advance.

**Comment by aumayr** [comment]
@corani I implemented a first version of this. Works on account names in tree-tables and the header of the Account view. If a file is dragged over such an area, the background of that area changes to light blue to indicate that a file can be dropped here. 

Things missing:
- Check if the document option is set, valid, and writeable
- Check if filename already contains date, and if not show a popup, etc.
- Automated tests

Can you try it out and give feedback if it does what you intended?

**Comment by corani** [comment]
Dropping on tables works great, but the header is a bit narrow. Is there any way to make the drop-target a bit bigger? (e.g. add some padding to the top and bottom of the header)

Some more things:
- It doesn't warn before overwriting a file
- Chinese characters (probably all non-latin characters) are stripped

**Comment by aumayr** [comment]
> Dropping on tables works great, but the header is a bit narrow. Is there any way to make the drop-target a bit bigger? (e.g. add some padding to the top and bottom of the header)

Will do.

> It doesn't warn before overwriting a file

Will implement that in step with the filename-date-check

> Chinese characters (probably all non-latin characters) are stripped

I think this is because of https://github.com/aumayr/fava/blob/master/fava/application.py#L115

**Comment by corani** [comment]
One more, it should create the correct parent folders if they don't yet exist.

**Comment by corani** [comment]
> I think this is because of https://github.com/aumayr/fava/blob/master/fava/application.py#L115

Looks like a likely culprit. This is low-prio for me, btw. I can live with latin-only

**Comment by corani** [comment]
Hmm, for some reason "data-account-name" has suddenly become empty in the tables, causing the documents to be uploaded to the root...

**Comment by corani** [comment]
Reading the beancount manual, I noticed _"You may specify this option multiple times if you have many such document archives."_ Another gotcha. If we need a dialog anyway to ask for the date to put in the filename, maybe also let the user pick the document-root, if there are multiple.

**Comment by aumayr** [comment]
> One more, it should create the correct parent folders if they don't yet exist.

> Hmm, for some reason "data-account-name" has suddenly become empty in the tables, causing the documents to be uploaded to the root...

Both fixed in 60e7c4db1ec65fe83906deb55edb273357fc7cef

**Comment by aumayr** [comment]
Remaining TODOs (will update here):

- [ ] Check if file is overriding an existing file
- [ ] Make drop target in Account view bigger
- [X] Support multiple root folders
- [X] Check if directory is existing and if not: create it
- [X] Check if filename starts with `YYYY-MM-DD.`
- [X] Upload multiple documents

**Comment by aumayr** [comment]
@corani I implemented the missing parts. Can you test again?

**Comment by corani** [comment]
All confirmed working. Awesome!

**Comment by aumayr** [comment]
👍
