### ISSUE TITLE
fava on cygwin

### ISSUE THREAD

**Issue by redstreet** [aumayr/fava#159]
This is an installation question. I've been running the erstwhile beancount-web on cygwin fine. The  last version I ran was c95dc (2016-01-09). Unfortunately, I'm unable to install the latest version on Cygwin.

If I install it by running "pip3 install beancount-fava", it fails when trying to compile libxml:
    error: Cygwin gcc cannot be used with --compiler=mingw32

That's a common error, and each solution is fraught with issues. I tried compiling with gcc (that my python interpreter is compiled with) and that failed too. I can't compile with VC++ for many reasons. Note that I have libxml2 installed, and therefore, a compile here should not be needed. Is this because libxml (and not "libxml2") is mentioned as the dependency? I haven't looked.

If I install fava by hand (cloning the repo and running "python3 setup.py install"), it seems to install fine. First issue: both methods of installation should yield the same result. Second issue: when I actually run fava, it shows me a broken barebones page with the correct data but one that seems to have its css missing. I haven't debugged further.

So, summarizing the questions:
- is fava supported on cygwin? Are people running it?
- do I really need python 3.5? I'm running python 3.4 currently
- why does the installation from the repo differ from a PyPI install?
- the issue with fava showing a page without css

**Comment by redstreet** [comment]
Update: tried to install from the repo onto a Linux system, and though the installation went smoothly, I still get a page without the css. The css part is my uneducated guess. Here is a screenshot:

![image](https://cloud.githubusercontent.com/assets/691755/13273033/7055a758-da55-11e5-9ccf-2fdb00b2bd1e.png)

**Comment by blais** [comment]
If the problem is downstream with the Beancount install, please let me know.
You can try installing Beancount using pip3 now, with

  pip3 install beancount

**Comment by redstreet** [comment]
@blais thanks, but I think Beancount looks fine. I installed the latest via pip3 after seeing the latest CHANGES, and everything seems to work fine with it so far.

**Comment by aumayr** [comment]
> is fava supported on cygwin? Are people running it?

I have not tried it yet, but will in a VM. 

> do I really need python 3.5? I'm running python 3.4 currently

Python 3.4 should be fine (the Travis CI tests run for 3.4 and 3.5, and both work)

> why does the installation from the repo differ from a PyPI install?
> the issue with fava showing a page without css

Installing from the repo (for development) changed recently, as we introduced `webpack.js` to handle all JavaScript dependencies and compile the SCSS. Therefore, CSS is not included in the repo (but in the PyPI-version, which is the latest "stable" one):

Here is the new workflow, which includes compiling the SCSS to CSS via `make build-js`, as in `README.md`:

> #### Development
> 
> If you want to hack on `fava`, this will get you up and running:
> 
> 
> ```bash
> git clone https://github.com/aumayr/fava.git
> cd fava
> # using a virtual environment is optional, but recommended
> virtualenv -p python3 venv
> . venv/bin/activate
> make build-js
> pip install --editable .
> ```
> 
> Note that you'll need to have the newest version of `npm` and `NodeJS` installed to build the JavaScript and CSS files.

**Comment by redstreet** [comment]
Ah ok, thanks for the explanation. I did read that part in the readme, but assumed it was only if I wanted to mention changes to the source code.
 
It might take me a little while to get my environment setup, and I'll get back as soon as I get that done. Thanks again!

**Comment by redstreet** [comment]
Closing, unless you want to reopen to check a cygwin install. I'll report back about cygwin either way.

**Comment by aumayr** [comment]
> I'll report back about cygwin either way.

I'll wait for you to report back until I start to install Windows in a VM ;-)

**Comment by redstreet** [comment]
Cygwin doesn't have the npm or node.js packages. npm's "Installing under cygwin" section has one word: "No.". That seems to say it all :). I'm not going to pursue this further on cygwin, and will find a linux box to try it on.

**Comment by aumayr** [comment]
> That seems to say it all :)

Oh, I didn't know that as well… Sorry for the inconvenience!

**Comment by redstreet** [comment]
Just a note: though developing fava on Cygwin might not be easy because of the issues above, it runs fine on Cygwin when installed through pip3. I'll can add a note to docs/usage.rst if you would like. Something like:

fava should be able to run wherever a Python 3 installation is available, and is known to run on Mac OSX, Linux, and Cygwin

**Comment by aumayr** [comment]
Yes, please do so :-)

**Comment by redstreet** [comment]
Basic question: I'm trying to build on a Linux system, and then install using pip on a Cygwin system. @aumayr  or anyone familiar with pip and with fava help? I'll update the documentation once I get this running.

**Comment by aumayr** [comment]
I have no real experience with Cygwin, so I am of no real help here… although I have some Windows-VMs lying around, so if you want me to try anything in particular, please let me know.

**Comment by redstreet** [comment]
Actually, there should be nothing specific to Cygwin. Consider it to be the same as a Linux system which doesn't have the build environment (eg npm), but has python and pip. What I'm really asking is how do I take the pip packages that get build on one system, and install it via pip on another system, if that's possible at all without going through PyPI.

**Comment by aumayr** [comment]
You do not have to go through `pip` at all, but you can use `setuptools` instead:

https://pythonhosted.org/setuptools/setuptools.html#bdist-egg-create-a-python-egg-for-the-project

**Comment by redstreet** [comment]
Great, thanks for the pointer!

**Comment by Shadowhandler** [comment]
What the fuck！！
