### ISSUE TITLE
Query-error: Type <class 'cdecimal.Decimal'> not recognized

### ISSUE THREAD

**Issue by alexjj** [aumayr/fava#166]
Firstly, this project is awesome! :cake: Did a git pull and rebuilt and there are new features!

Now that you've added exporting queries to csv/xls etc. I realised it would be more useful to separate number and currency into two columns. The number column is filled red and the type error appears. It doesn't really impact the functionality of the query, although when exporting to xls/ods it's not formatted as a number and it saves it as '12.34, which obviously means formula don't recognise it as a number.

For reference the query is:

```sql
SELECT 
    month, account, sum(number), currency
FROM
    year = 2016
WHERE 
    account ~ 'Expenses'
GROUP BY month, account, currency
ORDER by month, currency, account
FLATTEN
```

**Comment by aumayr** [comment]
There are some points in this:

> Query-error: Type <class 'cdecimal.Decimal'> not recognized

Where does this error occur? In the resulting CSV/XLS? In the HTML? Can you attach a screenshot, so we can pinpoint where this comes from?

> I realised it would be more useful to separate number and currency into two columns

Factored that out into it's own issue: #168

>  when exporting to xls/ods it's not formatted as a number and it saves it as '12.34, which obviously means formula don't recognise it as a number

Is it displayed as `12.34` instead of `12,34`? In which application are you opening the downloaded file? Excel? 

If Excel: The decimal separator is different for different languages - what language are you using Excel in?

> For reference the query is:
> 
> SELECT 
>     month, account, sum(number), currency
> FROM
>     year = 2016
> WHERE 
>     account ~ 'Expenses'
> GROUP BY month, account, currency
> ORDER by month, currency, account
> FLATTEN

Off-topic: This is a variant on http://aumayr.github.io/beancount-sql-queries/query/monthly-expenses-report.html, right? It would be nice if you could post (PR) a new query to the beancount-sql-queries-page with this (or a variant of it), because it does display the number and currency in two separate columns.

**Comment by alexjj** [comment]
> Where does this error occur? In the resulting CSV/XLS? In the HTML? Can you attach a screenshot, so we can pinpoint where this comes from?

In the HTML. I'm at work now so can't run fava, it was in the td class of the cell. I think the td class was either `<td class="cdecimal.Decimal">` or `<td class="Type-error" cdecimal.Decimal="1234.12">` I'll see if I can find a way to run it, otherwise I'll reply later (in about 10 hours) with a screenshot.

Interestingly when I run the same query in the pythonanywhere demo site it works perfectly well. The sum_number column is rendered as `<td class="num" data-sort-value="2400.00">2,400.00</td>`

I pulled the latest source last night and ran it.

> Off-topic: This is a variant on http://aumayr.github.io/beancount-sql-queries/query/monthly-expenses-report.html, right? It would be nice if you could post (PR) a new query to the beancount-sql-queries-page with this (or a variant of it), because it does display the number and currency in two separate columns.

Yes I thought about that when I was experimenting with the query.

**Comment by aumayr** [comment]
> Interestingly when I run the same query in the pythonanywhere demo site it works perfectly well. The sum_number column is rendered as `<td class="num" data-sort-value="2400.00">2,400.00</td>`

Can you confirm if this is still happening with the current version? If yes: Can you send an excerpt of the page source (HTML)? I can not reproduce this :-/

**Comment by alexjj** [comment]
Here's a screenshot:

![screenshot_2016-02-27_11-26-42](https://cloud.githubusercontent.com/assets/440939/13374862/2f3b9a28-dd45-11e5-8c93-f6be02b8f6c6.png)

The red cells have this html:
```html
<td class="query-error" title="Type <class 'cdecimal.Decimal'> not recognized">-2948.15</td>
```

**Comment by alexjj** [comment]
Okay it did matter.

Without m3-cdecimal it works fine, but with it I get the error. I installed m3-cdecimal because of the beancount warning and I think Martin suggested to in some thread on the mailing list.

**Comment by aumayr** [comment]
Sorry @alexjj for the long wait. e9dfcae should fix this, which is rather simple ;-)

Thanks for your patience, and the good documentation in the error report (screenshot, etc.).

**Comment by alexjj** [comment]
Thank you :+1:
