### ISSUE TITLE
Charts with by-year filter

### ISSUE THREAD

**Issue by cgrinds** [aumayr/fava#175]
Thanks for creating fava. It's really nice.

I have 26 years of data in beancount, and it would be great to have a by-year filter for the charts. For example the Income Statement chart has Monthly rollups, but no Yearly. 

Trial Balance has Yearly Balances and Changes, but seems like it might be useful for other charts too.

**Comment by corani** [comment]
Wow, 26 years? That's dedication! That motivates me to finally convert the five years history I still have in c-ledger to beancount. 

While adding a "yearly" chart is easy, it is getting a bit crowded below some of the charts (especially if you're using a couple different operating currencies, like me) 

I was thinking that it might be a better idea to add a select box to most of the charts with "Roll-up": weekly/monthly/yearly

@aumayr what do you think?

**Comment by aumayr** [comment]
@cgrinds Boah, 26 years is comprehensive :+1: 

I think @corani's concern is valid and suggestion is good: The "Roll-up"-select box totally makes sense.

**Comment by aumayr** [comment]
In fact, there could be even more charts, and these should be lazily loaded (async requests for their data) because with more charts the API-calls take a lot of time.

**Comment by aumayr** [comment]
Would something like this be enough? Or is there a better place/way to do the UI?

![screenshot](https://cloud.githubusercontent.com/assets/5135450/13378132/2ff06c18-ddfa-11e5-9bc5-96371462b268.png)

**Comment by corani** [comment]
Looks good to me

**Comment by cgrinds** [comment]
24 years of Quicken data, converted to Moneydance last Dec, then converted to beancount in Jan. I created a simple QIF -> beancount converter to do the heavy lifting. It's been a great way to validate the data and fixes issues in the source material.

The rollup looks good and I agree with the crowding below the charts statement.

**Comment by yagebu** [comment]
Looks good :+1: There should be a keyboard shortcut to toggle that also. Using `c` to go through the charts is quite comfortable :)

**Comment by aumayr** [comment]
@cgrinds I implemented this in the `chart-interval-switcher`-branch. Can you test the code from there if this works for you?

**Comment by cgrinds** [comment]
@aumayr looks great! Thanks for adding.

One suggestion - after making a selection in the rollup box, remember it when switching views, otherwise the new view always switches back to monthly. A small thing, but something I noticed.

One issue is the chart links aren't quite right. For example if viewing by year, when you click on the chart's bar, you will be taken to `income_statement/?interval=year&time=2012-01` instead of `income_statement/?interval=year&time=2012`

**Comment by aumayr** [comment]
@yagebu Can you help me implement two more cases for parsing "human-entered" dates? 

I marked them here: https://github.com/aumayr/fava/blob/chart-interval-switcher/fava/util/dateparser.py#L5-L6

**Comment by yagebu** [comment]
Will do.

**Comment by cgrinds** [comment]
Thanks all, looks great.
