### ISSUE TITLE
ImportError: cannot import name 'iter_entry_dates'

### ISSUE THREAD

**Issue by wogong** [aumayr/fava#180]
I installed the latest fava using `pip3 install --user fava` in arch. 

Environment info
* `Linux  4.4.1-2-ARCH #1 SMP PREEMPT Wed Feb 3 13:40:19 UTC 2016 i686 GNU/Linux`
* Python 3.5.1.
* Latest beancount `pip install --user --upgrade beancount`

However, I got following error messages running `fava`

```
$ fava
Traceback (most recent call last):
  File "/home/wogong/.local/bin/fava", line 7, in <module>
    from fava.cli import main
  File "/home/wogong/.local/lib/python3.5/site-packages/fava/cli.py", line 9, in <module>
    from fava.application import app, load_settings
  File "/home/wogong/.local/lib/python3.5/site-packages/fava/application.py", line 19, in <module>
    from fava.api import BeancountReportAPI, FilterException
  File "/home/wogong/.local/lib/python3.5/site-packages/fava/api/__init__.py", line 32, in <module>
    from beancount.core.data import (get_entry, iter_entry_dates, posting_sortkey,
ImportError: cannot import name 'iter_entry_dates'
```

**Comment by yagebu** [comment]
Please check the version of beancount that you've installed. `iter_entry_dates` was only added recently, so your version doesn't seem up-to-date.

**Comment by aumayr** [comment]
@yagebu Was `iter_entry_dates` added after the latest Version-release of Beancount (as `setup.py` relies on the PyPI-version of Beancount)?

**Comment by wogong** [comment]
Thanks for your info.
It seems that I have multiple Beancount installed using different methods.
I reinstall it from source using `hg update` and it works well now. :)

**Comment by yagebu** [comment]
@aumayr it was added in https://bitbucket.org/blais/beancount/commits/643d3de10807e572117f4ae53fe0408af3681648 and has been in all the releases since 2.0b4 (the first one working with `pip`)

**Comment by aumayr** [comment]
@wogong Good to hear that it works for you!

@yagebu Thanks for checking!
