### ISSUE TITLE
Custom query `bql` parameter mixed with `time` parameter

### ISSUE THREAD

**Issue by wzyboy** [aumayr/fava#181]
Doing a custom query after a time range is selected leads to URL parameter error:

`http://localhost:5000/query/?time=2016?bql=balances%20from%20year%20%3D%202015%3B`

The second `?` should be `&`.

**Comment by corani** [comment]
Fix in #186, the `?` was hardcoded in the URL.

**Comment by wzyboy** [comment]
Thanks @corani !

**Comment by corani** [comment]
Please wait for @aumayr to merge the PR before closing :wink:

**Comment by aumayr** [comment]
@wzyboy @corani Merged, thanks!
