### ISSUE TITLE
Display metadata that attached to postings

### ISSUE THREAD

**Issue by wzyboy** [aumayr/fava#184]
I just found that metadata could be attached not only to transactions, but also to postings: [Beancount - Language Syntax §Metadata](https://docs.google.com/document/d/1wAMVrKIA2qtRGmoVDSUBJGmYZSygUaR0uOMW1GV3YE0/edit#heading=h.dplfcfjm39a1). (Not sure if Martin added this syntax recently or there is a memory gap in my head.)

However in Fava, only metadata that attached to transactions are shown. It would be nice if metadata attached to postings could be shown as well.

**Comment by corani** [comment]
Good catch!

**Comment by aumayr** [comment]
Fixed in #185
