### ISSUE TITLE
Decimal display improvements

### ISSUE THREAD

**Issue by wzyboy** [aumayr/fava#187]
Some currencies (like JPY, KRW), or some non-currency commodities (like credit card rewards "points"), do not use fractional parts in the real world. But Fava seems to display fractional parts anyway.

If all the transactions of a certain commodity (e.g. JPY) use only integers, `bean-query` and `bean-web` displays the amounts as `100 JPY`, but in Fava `100.00 JPY`. Could Fava hide the fractional parts if all the transactions use integers?

**Comment by wzyboy** [comment]
I am not sure, but the use of `dcontext` may help address this issue...

**Comment by aumayr** [comment]
@wzyboy Can you confirm that this is fixed?

**Comment by wzyboy** [comment]
@aumayr I pulled and tested. This is fixed.

**Comment by aumayr** [comment]
👍
