### ISSUE TITLE
Don't auto-reload when there are unsaved changes

### ISSUE THREAD

**Issue by corani** [aumayr/fava#191]
When you drop a document into the document folder while editing a source file, the page is reloaded and all your changes are lost.

**Comment by wzyboy** [comment]
IMHO generally there should be a warning when there are unsaved changes in the editor box. Close the browser tab when there are unsaved changes should also trigger this warning.

**Comment by corani** [comment]
A third case: when you have unsaved changes and switch the source file you're working on, your work is lost.

**Comment by aumayr** [comment]
I have seen my mom running into this issue a couple of times - she did just forget to save the changes, and wanted to check if there are errors... fixing this is important to avoid frustration.
