### ISSUE TITLE
Query Editor: Can't execute saved query with changes

### ISSUE THREAD

**Issue by corani** [aumayr/fava#192]
When you load a saved query in the query editor, make some changes to it and submit it, the original saved query is executed and your changes are lost.

When you make any changes in the query editor, either (1) the `query_hash` parameter should be cleared, or (2) when a `bql` parameter is present, that should be used as the query instead.

Option (2) might allow for a `Reset` button, which could be useful.

**Comment by yagebu** [comment]
I don't see any point in keeping the `query_hash` in the URL. If a user presses the "Submit Query" button, the query was changed (why else would you want run the query) so the `query_hash` will not be consistent with the query string and should be ignored anyway.

**Comment by corani** [comment]
It's there to highlight the correct query in the sidebar and select box, though I see your point. I'd be okay with loosing the highlight after submitting a query.

Alternatively, maybe we could execute the query asynchronously? That would improve responsiveness, and at least ensure we don't loose the highlight of the select box.

**Comment by yagebu** [comment]
> It's there to highlight the correct query in the sidebar and select box, though I see your point.

The problem is that it's unclear if we can even determine the "correct" query. We would have to check if the text changed, which too much hassle IMHO. I'll submit a PR removing the query_hash.

> Alternatively, maybe we could execute the query asynchronously? That would improve responsiveness, and at least ensure we don't loose the highlight of the select box.

:+1: that would be the right way to bring back the highlight!
