### ISSUE TITLE
Query Editor: Add `source` link for saved queries

### ISSUE THREAD

**Issue by corani** [aumayr/fava#193]
Rationale:
When you want to permanently change a saved query, depending on how your source files are organized, it can be cumbersome to locate the query.

Proposed solution:
Below the query editor (e.g. left of the `Submit Query` button), add a link to the source file at the location where the specific query is located.

**Comment by aumayr** [comment]
Sounds good, and should be easy to implement.

**Comment by corani** [comment]
Adding a link to a context page is easy enough, as is adding a link for static query pages (those loaded with a `query_hash` parameter).

However, for dynamically loaded queries (changing the query from the select box) it's a bit more tricky, as we only have the `query_hash`, but not the source file and line number.

Any ideas how to solve this?

**Comment by aumayr** [comment]
We could store more than just the `query_hash` in the `value="..."`-attribute of the `<select>`, like `value="[query_hash];[source_file];[lineno]"`, and then split that value in the part of the JavaScript-code that submits the form and use it accordingly.
