### ISSUE TITLE
Flagged transaction journal

### ISSUE THREAD

**Issue by corani** [aumayr/fava#196]
To quickly find all flagged transactions, create a new journal page for them (alternatively, create a filter-by-flag)

**Comment by yagebu** [comment]
For this we already have the toggle boxes on the journal page.

**Comment by corani** [comment]
Ah, I see. However, this doesn't work correctly.

When I only select "pending", many pages of balance-assertions, notes, documents, etc drown out the few flagged transactions. I need to uncheck all those types of entries as well, which is not expected (and probably why I didn't figure this out myself!)

**Comment by corani** [comment]
Also, transactions with flagged legs don't show up, since the toggle-box filters only apply to flags on the entire transaction.

**Comment by yagebu** [comment]
> When I only select "pending", many pages of balance-assertions, notes, documents, etc drown out the few flagged transactions.

Only transactions have flags, so the second row of filters can only apply to them. And as long as the `balances` box is still checked they are still supposed to show up.

**Comment by corani** [comment]
According to the docs:

> You can also attach flags to the postings themselves, if you want to flag one of the transaction’s legs in particular:
```
2014-05-05 * "Transfer from Savings account"
  Assets:MyBank:Checking            -400.00 USD
  ! Assets:MyBank:Savings
```

**Comment by yagebu** [comment]
I was only referring to entries and of those only transactions can have flags. There is no way to filter the journal for postings or metadata currently (and maybe there should be), but we shouldn't overload the form with the filter boxes too much.

**Comment by corani** [comment]
Since `*` (cleared) is the default flag (the same as not using any flag), I would expect that unchecking that box would also hide anything without flags (such as balance, note, document, etc)

Having said that, I agree that the current four levels of filters are confusing. (navigation bar, two levels of checkboxes and two buttons)

**Comment by yagebu** [comment]
> (the same as not using any flag)

But every transaction has a flag (and no other entry type does). Only entries that have a flag can be cleared, and hence only transactions will be toggled with this box. It could be made more obvious that these toggle boxes only apply to transactions with some CSS I guess.

> Having said that, I agree that the current four levels of filters are confusing. (navigation bar, two levels of checkboxes and two buttons)

There shouldn't be any more filters (meaning those in the navbar) IMHO, but we should alternatively allow to filter the entries with a BQL `FROM`-expression.

**Comment by corani** [comment]
> But every transaction has a flag

How about this one?

```
2016-03-09 txn "payee" "narration"
  Assets:Bank                   1 EUR
  Income:Tree
```

> In the case of the first example using “txn” to leave the transaction unflagged, the default flag (“*”) will be set on the transaction object.

**Comment by yagebu** [comment]
> filter the entries with a BQL FROM-expression.

As far I can see, that currently wouldn't be enough for your purpose, as the only posting attribute the `from` syntax seems to currently support is account (through `has_account`). But I believe it would be a sensible addition.

> How about this one?

"the default flag (“*”) will be set on the transaction object." => every transaction has a flag

**Comment by aumayr** [comment]
First: Making the filters "permalink-able" by adding support for GET-parameters controlling the default-value of the filters seems like a first goal to support new use-cases ("Just show me flagged ones" => set a bookmark to do this). 

If we decide to add a separate link in the sidebar explicitly for certain use-cases, it would be easy by just linking to those "permalinks". 

For the filtering: There is, undoubtedly, a lot more "potential" in the Journal filters. For me, they work pretty well right now, as I do not have any use-cases that are not possible with the current filter layout. But filtering by metadata sounds very nice, as well as more advanced things. Do you have any suggestions for how we might re-layout the filters for the Journal page?

**Comment by corani** [comment]
I like the idea of being able to permalink certain journal filtered views in the sidebar. That would be a very useful addition.
