### ISSUE TITLE
Source Editor: Position is lost on save

### ISSUE THREAD

**Issue by corani** [aumayr/fava#197]
When saving a source file the current position is lost. The editor reverts back to line-1 of the main source file.

**Comment by aumayr** [comment]
@corani This works for me - the cursor stays in the same line (but column 1) when I click "Save" in the Source editor.

**Comment by corani** [comment]
I just noticed that things work fine in debug mode (`--debug`), but not in normal mode. No idea why that should make a difference though...

**Comment by yagebu** [comment]
The difference could be that `livereload` is not enabled in debug mode currently

**Comment by corani** [comment]
Good point! So probably `livereload` triggers a page reload before the `save` action has had the chance to redirect the user to the correct page (including filename and lineno)

**Comment by aumayr** [comment]
Ahh of course, good catch @corani and @yagebu. 

Because on a "Save" the file is changed on the disk, `livereload` reloads the page (as it should when a source file on disk changes.)
