### ISSUE TITLE
Check out graphics from ledgible

### ISSUE THREAD

**Issue by aumayr** [aumayr/fava#198]
https://github.com/lipidity/ledgible

**Comment by corani** [comment]
The [sunburst chart](https://lipidity.com/cgi/ledgible/app.py/sunburst?a=^Expenses&a=^Income) is kind of fancy (though [this presentation](http://bl.ocks.org/kerryrodden/7090426) is a bit better)

**Comment by aumayr** [comment]
This looks very nice :heart_eyes:

Will see how I can build this into fava. One problem I instantly see: This takes up a lot of space, so it probably would need it's own page. And the question is for which "data" to show this - the trial balance? For single Account pages?

What also would be nice, now that new graphics are on the table: https://github.com/DKirwan/calendar-heatmap would be a nice way to give an overview of accounts that have daily transactions, like when you are a business and you have many small invoices.

**Comment by corani** [comment]
Hi like the calendar-heatmap!

Maybe we can use it to show amounts as well on the Income Statement,
instead of the current bar-chart, when the interval is "daily".

On Tue, Mar 15, 2016 at 2:52 PM, aumayr <notifications@github.com> wrote:

> This looks very nice [image: :heart_eyes:]
>
> Will see how I can build this into fava. One problem I instantly see: This
> takes up a lot of space, so it probably would need it's own page. And the
> question is for which "data" to show this - the trial balance? For single
> Account pages?
>
> What also would be nice, now that new graphics are on the table:
> https://github.com/DKirwan/calendar-heatmap would be a nice way to give
> an overview of accounts that have daily transactions, like when you are a
> business and you have many small invoices.
>
> —
> You are receiving this because you commented.
> Reply to this email directly or view it on GitHub:
> https://github.com/aumayr/fava/issues/198#issuecomment-196689473
>



-- 
Best regards,
Daniël Bos


Your government is reading your email. Slow them down with encryption.

My public key: http://goo.gl/gms497 (4096 bit RSA, id EF2D5D91)
Fingerprint  : D8D0 9FBE F075 F709 7B52  2F73 326C 2123 EF2D 5D91

**Comment by aumayr** [comment]
For the sunburst chart:

Right now the charts are about 250px high, and this one would have to be much higher. Would it be OK if this chart is integrated where the others are right now, but will become much higher when clicked? Or would be a separate page/subpage more appropriate?

**Comment by yagebu** [comment]
> Would it be OK if this chart is integrated where the others are right now, but will become much higher when clicked?

I think it's nice to have it on the same page, so :+1:

**Comment by corani** [comment]
That seems in-line with the "drill-down" concept. Perhaps it's possible to show only one (or two) levels in the sunburst chart while it's collapsed, so you get a high-level view. Clicking on it would show all the levels in a larger overlay, so you can drill down further.

**Comment by aumayr** [comment]
Related:

- http://dimplejs.org (https://news.ycombinator.com/item?id=11369756)
- https://dc-js.github.io/dc.js/
- https://github.com/wrobstory/vincent
- https://plot.ly/javascript/

**Comment by yagebu** [comment]
When I made the switch to webpack for the bundling our javascript files I ran into some problems with Chartist. Now again I've invested some time to look at the other available charting libraries. I mostly agree with this comment: https://news.ycombinator.com/item?id=11372145.

Most charting libraries, by trying to simplify the process of creating charts, make it much harder to customize anything. There's no one size fits all, which leads to duplicate code. I definitely want to have the following charts:

- Historical bar and line charts. For these a more advanced charting library seems to have the most benefit, if it has good axis renderers, builtin support for pan and zoom, and a preview chart. These advanced features seem to be impossible to do with Chartist (or only with more buggy plugins).
- Sunburst charts. None of the charting libraries support them out of the box (except for nvd3, which is just a mess), so for these we have to write something based on d3.
- Treemaps. Dito. (What we currently have is not really a treemap, as it completely ignores the hierarchical structure)

Another point is documentation. d3 has well-written and complete documentation, and this should definitely be a strong criterion for selection of a charting library. `dc-js` and `dimple` actually seem to have decent docs. Plotly seems to do too much that we don't need and vincent doesn't seem to be developed anymore so I wouldn't really consider them.

So far I'm yet to be convinced that any of these libraries built on d3 are actually well-designed, often they just seem to be convoluted mess of features. d3 is quite nicely modularized (and the upcoming d3 4 will have even less quirks). There's a wealth of instructive examples and some good reads at Mike Bostock's [website](https://bost.ocks.org/mike/)

I propose implementing a treemap and sunburst chart (I can work on the former) directly with d3. The line and bar charts work with Chartist for now, so they're not such a pressing issue. If we work on them, we should consider using a different charting library but should also see how much effort it would be to do them in d3.

PS: [plottable](http://plottablejs.org/) might be another option.

**Comment by aumayr** [comment]
> I propose implementing a treemap and sunburst chart (I can work on the former) directly with d3.

Agreed. The [link of the sunburst chart @corani posted](http://bl.ocks.org/kerryrodden/7090426) is implemented in d3, so using that should be no problem.

**Comment by aumayr** [comment]
@yagebu I implemented the sunburst chart on top of #252. When you merge I will clean up my code and add a PR.

**Comment by aumayr** [comment]
Thanks @corani and @yagebu for the help!

I will close this issue, but feel free to reopen it if you find any bugs or annoyances with the current implementation.

**Comment by corani** [comment]
The new treemap and sunburst don't work for me.

Treemap:
- When I select "Assets (CNY)", I get only one entry: Cash, with the value of my Assets:Cash in USD.

Sunburst: 
- While the size of the sections looks correct, the labels are all incorrect. Most of them are 0, some of them have amounts in the wrong currency (for example, all my Assets:Cash sections show the amount in USD)
- Equity shows only "OpeningBalances", not the other categories (Conversions, Corrections, Earnings)
- I have "X" posted in "Assets:Receivable", and an additional "Y" posted in "Assets:Receivable:Pension", however, the "Receivable" section is only as large as "Y".

**Comment by aumayr** [comment]
@corani Thanks for reporting - I see the same bugs.

**Comment by yagebu** [comment]
Should be fixed.

> Equity shows only "OpeningBalances", not the other categories (Conversions, Corrections, Earnings)

This is not really a bug When no time filter is set, accounts aren't closed so these entries aren't generated. But maybe it would make sense to always close on "today" if nothing else is specified, and always generate the closing entries.

**Comment by corani** [comment]
@yagebu Treemap looks fixed, however, it now shows all of the first four charts on the page, the links below the charts have stopped working, and it only shows the first few links (up until the second operating currency for "Assets").

Additionally, I get the following error:
`Uncaught TypeError: Cannot read property 'length' of undefined`

**Comment by aumayr** [comment]
@yagebu I can second what @corani reports - same error.

**Comment by corani** [comment]
This fixes the issue for me, but it's a hack...
```
diff --git a/fava/static/javascript/charts.js b/fava/static/javascript/charts.js
index 64c7161..dda635e 100644
--- a/fava/static/javascript/charts.js
+++ b/fava/static/javascript/charts.js
@@ -35,7 +35,7 @@ function addInternalNodesAsLeaves(node) {
     $.each(node.children, function(i, o) {
         addInternalNodesAsLeaves(o);
     });
-    if (node.children.length) {
+    if (node.children && node.children.length) {
         var copy = $.extend({}, node)
         copy.children = null;
         copy.dummy = true;
@@ -438,7 +438,7 @@ module.exports.initCharts = function() {
                     var div = chartContainer(chart.id, chart.label + ' (' + currency + ')');
                     addInternalNodesAsLeaves(chart.root);
                     var treemap = treeMapChart()
-                        .value(function(d) { return d.balance[currency] * chart.modifier; })
+                        .value(function(d) { return (d && d.balance) ? d.balance[currency] * chart.modifier : NaN; })
                         .tooltipText(function(d) { return d.balance[currency] + ' ' + currency  + '<em>' + d.account + '</em>'; })
 
                     div
```

**Comment by redstreet** [comment]
Hierarchy and colors in the treemap are great now! Interaction is also sharp and responsive, and the labels are neat too!

Some questions:
- I'm slightly confused by the hierarchy in representation. I see that "families" of accounts (parent + children of that parent) are in the same color, which is great
 - what happens when no parent account exists, but only siblings (eg: Expenses:Car:Insurance, Expenses:Car:Fuel exist, but Expenses:Car does not exist, or exists but has no transactions in the selected period)?
 - regardless, would be it possible to make the border thicker around account families so the delineation is clearer?

- does ````treemaps-show-negative-numbers```` still work? I can't seem to get it to work

**Comment by redstreet** [comment]
Sunburst is very nice too!

It would be nice if it were possible to "drill down" into the sunburst, and have a sunburst rooted at the newly selected account. As an excellent and intuitive example of such interactivity, may I suggest a program that I've used for a long time: http://www.hdgraph.com/ Unfortunately, it's Windows only, so let me know if you can't run it, and I'll see if I can put up some animated demos.

**Comment by yagebu** [comment]
> I'm slightly confused by the hierarchy in representation. I see that "families" of accounts (parent + children of that parent) are in the same color, which is great

The color is determined by the name of the parent account unless that parent is the root, then it's determined by the name of the account itself.

> what happens when no parent account exists, but only siblings (eg: Expenses:Car:Insurance, Expenses:Car:Fuel exist, but Expenses:Car does not exist, or exists but has no transactions in the selected period)?

I don't really understand the question. Is this about the layout or the colors?

> regardless, would be it possible to make the border thicker around account families so the delineation is clearer?

Done (now 2px)

> does treemaps-show-negative-numbers still work? I can't seem to get it to work

It's a noop. I've just removed the setting. Ref #252.

**Comment by yagebu** [comment]
> It would be nice if it were possible to "drill down" into the sunburst, and have a sunburst rooted at the newly selected account. As an excellent and intuitive example of such interactivity, may I suggest a program that I've used for a long time: http://www.hdgraph.com/ Unfortunately, it's Windows only, so let me know if you can't run it, and I'll see if I can put up some animated demos.

Like this https://bl.ocks.org/mbostock/4348373?

**Comment by redstreet** [comment]
> Like this https://bl.ocks.org/mbostock/4348373?

Yes, exactly.

**Comment by redstreet** [comment]
>> does treemaps-show-negative-numbers still work? I can't seem to get it to work

> It's a noop. I've just removed the setting. Ref #252.

It's still useful for financial software to display negative balances. This occurs in many cases for me. So is there any chance you could reconsider leaving that in as an option as it was before? Thanks!

**Comment by yagebu** [comment]
> It's still useful for financial software to display negative balances. This occurs in many cases for me. So is there any chance you could reconsider leaving that in as an option as it was before? Thanks!

I don't think that displaying negative balances in a treemap is well-defined behaviour. I'm against adding an option for it if we can't make it the default, as this will add some more untested code.

**Comment by redstreet** [comment]
> I don't think that displaying negative balances in a treemap is well-defined behaviour.

We can define the behavior well for our specific use case. Practically speaking, @aumayr had put this in earlier and I was using this actively until the functionality broke for me.

> I'm against adding an option for it if we can't make it the default, as this will add some more untested code.

I can certainly add tests if that's the problem. Or are you saying that options set to non-default values are not easy to test?

Anyway, let me see if I can make a case for its usefulness. @aumayr if you could please point me to the code that you had in there earlier that allowed this to work, I'll take a look and activate it for myself first. @yagebu, if I try to restore (just for myself) the earlier code for your version of treemaps, do you foresee problems I might run into? Thanks!

**Comment by aumayr** [comment]
@redstreet This is where the code for the option `treemaps-show-negative-numbers` was removed:

https://github.com/aumayr/fava/pull/252/files#diff-7bca613d5b8880c23470aee53430257cL18

The version prior to this (PR #252) had the old chart-code, which included this option.

I'm on @redstreet's side of this argument, if the behavior is well defined (we can certainly do that) and tested (showing the intentions in code as well). There are other options in fava which are not enabled by default, so that shouldn't be a showstopper as well. Maybe you can try to integrate it in the new version of the treemaps (`d3.js`-based), add tests and documentation, and submit a PR so we can discuss it, @redstreet?

**Comment by redstreet** [comment]
> Maybe you can try to integrate it in the new version of the treemaps (d3.js-based), add tests and documentation, and submit a PR so we can discuss it, @redstreet?

Yes, sounds good. And thanks for the code pointers!

**Comment by yagebu** [comment]
> I can certainly add tests if that's the problem. Or are you saying that options set to non-default values are not easy to test?

For these frontend things, we don't really have a good way to write tests (and adding one is overkill at this stage IMHO), so the only way to find out if something breaks is by going through all the pages.

> Practically speaking, @aumayr had put this in earlier and I was using this actively until the functionality broke for me.

What we had before was not really a treemap chart (it didn't care for the hierarchy) and with a real treemap negative balances pose some additional problems. Say you have one account with 0 balance that has two sub-accounts, one with large negative, one with large positive balance, then it should occupy no area, but it does because we have to show its children. This is already a problem with the current version, but at least it's consistent: We just ignore accounts with negative balances in the hierarchy.

I don't see the old version of showing negative balances as a viable concept for the new treemaps. One thing that could work: Showing two treemaps - one with all the accounts with negative and one with all the ones with positive balance.

> @yagebu, if I try to restore (just for myself) the earlier code for your version of treemaps, do you foresee problems I might run into? Thanks!

It won't really help you. This would have to happen in Javascript now.
