### ISSUE TITLE
Only the first currency can display a net worth chart.

### ISSUE THREAD

**Issue by miaoluda** [aumayr/fava#207]
![fava bug 1](https://cloud.githubusercontent.com/assets/14816337/13734688/6f4e6328-e9db-11e5-82cd-960e5b62e296.png)
![fava bug 2](https://cloud.githubusercontent.com/assets/14816337/13734691/791ffbd2-e9db-11e5-8e3d-84017f7dc2ac.png)

Reproduce:
Add the following lines to example.beancount: 
```
option "operating_currency" "DSU"
option "operating_currency" "SUD"

2015-01-01 open Assets:SU:FakeBank                        DSU,SUD
2015-01-01 open Income:SU:FakeCompany:Salary                        DSU, SUD

2015-01-31 * "FakeCompany" | "Payroll"
   Income:SU:FakeCompany:Salary                         -10000.00 DSU
   Assets:SU:FakeBank                                    10000.00 DSU
	
2015-01-31 * "FakeCompany" | "Payroll"
   Income:SU:FakeCompany:Salary                         -7777.00 SUD
   Assets:SU:FakeBank                                    7777.00 SUD
```

**Comment by yagebu** [comment]
Thanks for the report! I think I've discovered the reason for this bug and should be able to provide a fix today.
