### ISSUE TITLE
Editor: Support code folding

### ISSUE THREAD

**Issue by corani** [aumayr/fava#208]
Add the possibility to fold regions of source files. In the beancount documentation, Martin gives the example of org-mode:

```
* Banking
** Bank of America

2003-01-05 open Assets:US:BofA:Checking
2003-01-05 open Assets:US:BofA:Savings

;; Transactions follow …

** TD Bank

2006-03-15 open Assets:US:TD:Cash

;; More transactions follow …
```

Alternatively, [C-style folding](https://github.com/ajaxorg/ace/wiki/Non-Standard-Code-Folding) could be implemented.

This is useful if you organize your source files not purely chronologically, but grouped by institution.

**Comment by aumayr** [comment]
Fixed in #209 (01a6582b32dc5e6a5ac84db6c42009622f52a312)
