### ISSUE TITLE
Editor: Sensible tabsize default

### ISSUE THREAD

**Issue by aumayr** [aumayr/fava#211]
In my beancount file I use a tabsize of 2 spaces, because it looks best to my eyes. 

The current default is 4 spaces. Is there a recommendation by @blais / the beancount docs or any other reference for which tabsize to use?

**Comment by corani** [comment]
I use an indent of two spaces as well, the larger tab size is convenient
though, for aligning the amounts. With tab size of two, you'd be tabbing
forever!

**Comment by blais** [comment]
Haven't even thought about it.
I use two spaces to indent my postings.

**Comment by aumayr** [comment]
@corani The "tabbing forever"-argument is valid. Will close as `wontfix`.
