### ISSUE TITLE
Number should be clickable in Monthly Change view

### ISSUE THREAD

**Issue by yegle** [aumayr/fava#212]
In /account/$ACCOUNT/monthly_changes/ view, the number listed there should be link to a view that list all transactions in that month that affect the balance of this account.

Or better, I'd like to be able to hover on the number and list the transactions in a popup menu.

**Comment by corani** [comment]
This shouldn't be hard, for each cell we have the `account` and the `time`, so we can easily construct a link to `/account/$ACCOUNT/?time=$TIME`, though I suggest to make the entire cell clickable, not just the number.

**Comment by aumayr** [comment]
I don't like popups, but the link sounds good!

**Comment by aumayr** [comment]
@yegle @corani I implemented this in PR #283 

Can you test if this works for you?

**Comment by corani** [comment]
Works for me
