### ISSUE TITLE
Switch between multiple root source files

### ISSUE THREAD

**Issue by corani** [aumayr/fava#213]
Imagine you are responsible for multiple finances, e.g. your _personal_, your _side-business_ and some volunteer _organization_. Obviously you wouldn't want to mix those into one source file, so you keep separate source files, each with their own account hierarchy.

Currently you'd have to restart fava with different command-line arguments, to be able to switch between them. I'd like to be able to switch between them more naturally, e.g. from a dropdown menu in the topbar. I imagine this could replace the current `Beancount` title.

**Comment by aumayr** [comment]
Ahh this is a very good idea! 

I personally have multiple ones (my own, my Mom's side business, my Dad's car restoration project), and so this would be much welcomed! 

A few thoughts:

- You could start it by using `fava [file1] [file2] ...`
- Switcher, as you suggested, at the top left (the title of the beancount file as a (nicely styled) dropdown/`<select>`)
- As the application is practically "stateless", meaning every view can be recreated by a permalink with the correct `GET`-params, the currently selected beancount file would have to be tracked via a `GET`-param as well (like `?b=1` for the first file in the "list of root-files" (`file1` in the sample above), etc.)
- #214 would allow settings per beancount file (currently there is just a "global" settings file, which would apply to all "instances"). Settings per beancount file would be very nice!

**Comment by yagebu** [comment]
Good suggestion!

> As the application is practically "stateless", meaning every view can be recreated by a permalink with the correct GET-params, the currently selected beancount file would have to be tracked via a GET-param as well (like ?b=1 for the first file in the "list of root-files" (file1 in the sample above), etc.)

I would prefer keeping the file in the main part of the URL. I think `/title/report` where title is simply the title of the beancount file makes the most sense conceptually.

**Comment by aumayr** [comment]
> I would prefer keeping the file in the main part of the URL. I think `/title/report` where title is simply the title of the beancount file makes the most sense conceptually.

Agreed, putting it in the Path-part of the URL is better.

**Comment by corani** [comment]
One thing that immediately tripped me up: make sure you have a

```
option "title" "Something"
```

in each of your root source files, otherwise you'll see only one of them.

**Comment by aumayr** [comment]
@corani Good point! We should have a check for that on startup, throwing an error when missing.

**Comment by corani** [comment]
One more thing: the foreground color in the select box is white, so non-selected options are shown as white-on-white.

**Comment by aumayr** [comment]
Which browser are you using? Can you upload a screenshot?

**Comment by corani** [comment]
Chromium 49.0.2623.108 Ubuntu 14.04 (64-bit)

![screenshot from 2016-04-29 16 21 14](https://cloud.githubusercontent.com/assets/480775/14911225/89c4e7c6-0e26-11e6-8835-7aec3d9bc002.png)

**Comment by yagebu** [comment]
I think it would be easiest if the available files should show up on hover like the filters. I guess we could just reuse the CSS we use there and replace the select with a link list.

**Comment by corani** [comment]
Thanks @yagebu. Two issues left:
- The z-index is probably too low (it goes behind the chart legend)
- No down-arrow indicator

![screenshot from 2016-04-30 14 04 23](https://cloud.githubusercontent.com/assets/480775/14934213/9b8a2096-0edc-11e6-9167-f483ce6c6a0d.png)

**Comment by yagebu** [comment]
> The z-index is probably too low (it goes behind the chart legend)

#271 ;)

> No down-arrow indicator

Added.

**Comment by jacobburrell** [comment]
Could someone add this to the README or in a guide somewhere?

I had to search to find this feature.
