### ISSUE TITLE
Filter entries by arbitrary FROM expressions

### ISSUE THREAD

**Issue by aumayr** [aumayr/fava#217]
from #210

**Comment by yagebu** [comment]
Splitting this into two issues as they are not really related IMHO.

We should really support filtering entries by BQL FROM expressions, as this will combine their power with all the nice reports we provide (and will avoid setting up a different complicated way to filter entries).

The way I intend to implement this in the coming weeks, is to provide a switch to change from the current four filters to one input field where you can write any FROM expression (the old system will continue to work and might produce a from expression in the background).

**Comment by aumayr** [comment]
@yagebu Still interested in this?

**Comment by yagebu** [comment]
Yes, I've got a branch lying around that implements half of this already. Will try to at least get a PR with the backend stuff done this week.

**Comment by jbms** [comment]
I'd just like to chime in and say that I think this would be extremely useful.  One of the key things that I'd like to do with fava is view expenses and look at the breakdown.  However, it is important to be able to exclude certain categories, like taxes.  Right now I don't see any way to do that.
