### ISSUE TITLE
missing CSS/JS

### ISSUE THREAD

**Issue by draug3n** [aumayr/fava#219]
Well, title says it all. I've been running fava quite happily as a service (under cygwin, in windows). Recently upgraded to latest git (default branch), with no CSS/JS - all I see is 'naked' html. Installed latest release available in pip - no difference. Ran it in a terminal, so I could see the pretty text - no difference, and no errors reported.

Fava is otherwise functional - I can click around at tags, etc. and get the corresponding tables. Just not so pretty.
![fava screenshot](https://cloud.githubusercontent.com/assets/4015985/13898531/c2ee6c42-edd4-11e5-802b-45402f16c2b5.png)

**Comment by aumayr** [comment]
For running fava from the lastest git-version you need to compile the CSS and JS:

(Assuming you have Node.JS installed): `make build-js`

This generates/combines all the CSS and JS necessary. 

The pip-version should have these files already included, as we generate them prior to uploading to PyPI.

**Comment by aumayr** [comment]
See also https://aumayr.github.io/fava/development.html

**Comment by draug3n** [comment]
Well, there's the rub. I get no CSS/JS - even when I install from pip.

**Comment by aumayr** [comment]
So it still does not work for you?

**Comment by draug3n** [comment]
I'm good now. Needed to force removal of fava from python's site_packages directory to force reinstall from pip3.

------------------------------------------

Tried building the CSS/JS from source - but got lots of interesting errors, mostly of the following sort:

    fatal: '/cygdrive/c/Users/marti/AppData/Roaming/npm-cache/_git-remotes/git-https-github-com-lrgalego-jquery-treemap-git-c1ffaf95/C:\Users\marti\AppData\Roaming\npm-cache\_git-remotes\git-https-github-com-lrgalego-jquery-treemap-git-c1ffaf95' does not appear to be a git repository

I am fully prepared to chalk this up to me running in a very edge-case environment.

**Comment by aumayr** [comment]
OK good to hear it works now. 

@corani Aren't you running on Windows/Cygwin as well?

**Comment by corani** [comment]
Nope, Ubuntu Linux here.

**Comment by aumayr** [comment]
@corani Oh, sorry :-)
