### ISSUE TITLE
Make "copy balance directive" feature available everywhere

### ISSUE THREAD

**Issue by redstreet** [aumayr/fava#224]
This is the feature that copies the balance directive to the clipboard when the green/yellow/red dot is clicked on. This works from the table in the Statistics page, but it would be great if it worked from everywhere i.e., the balance/income statement pages, etc.

Reason 1: I find myself frequently focusing on a certain account, and having to go to the statistics page just to copy the directive is not as easy just clicking on the dot. Reason 2: consistency.

Thanks!

**Comment by yagebu** [comment]
Good idea!
