### ISSUE TITLE
Custom queries very slow

### ISSUE THREAD

**Issue by redstreet** [aumayr/fava#226]
This is probably a design issue to be discussed, hope filing this as an issue here is okay.

When I have a handful of custom queries I want to run one after the other, bean-query is almost instantaneous for each query I run, after the initial startup time (long in my case, since I have thousands of transactions and many plugins). With fava, however, each query takes on the order of half a minute to run. This makes custom queries almost unusable for me.

Is this because it's calling bean-query in the backend for each query separately, so the startup time (presumably for the backend to read the pickle file) is paid each time?

**Comment by yagebu** [comment]
> Is this because it's calling bean-query in the backend for each query separately, so the startup time (presumably for the backend to read the pickle file) is paid each time?

Nope, fava only loads the file once on startup (or when it's changed) and calls into beancount directly to run the query. The only thing we then to is to render it in the template and I would be surprised if that takes more than 1 or 2 seconds for very large tables.

Can you run fava with profiling enabled?

**Comment by redstreet** [comment]
You're right, most of the time is spent in beancount:

````
GET.query.023268ms.1458588906.prof

         17546308 function calls (17124616 primitive calls) in 23.268 seconds

   Ordered by: internal time
   List reduced from 692 to 25 due to restriction <25>

   ncalls  tottime  percall  cumtime  percall filename:lineno(function)
629306/217906   10.412    0.000   21.732    0.000 /usr/lib/python3.4/site-packages/beancount-2.0b8-py3.4-cygwin-2.4.1-x86_64.egg/beancount/core/compare.py:18(stable_hash_namedtuple)
  4172311    2.728    0.000    2.730    0.000 {built-in method isinstance}
  3681951    1.668    0.000    1.668    0.000 {method 'update' of '_hashlib.HASH' objects}
   879351    1.565    0.000    1.565    0.000 {method 'format' of 'str' objects}
  3682835    1.416    0.000    1.416    0.000 {method 'encode' of 'str' objects}
   637534    1.122    0.000    1.122    0.000 {method 'hexdigest' of '_hashlib.HASH' objects}
   439314    0.873    0.000    1.993    0.000 /usr/lib/python3.4/site-packages/beancount-2.0b8-py3.4-cygwin-2.4.1-x86_64.egg/beancount/core/display_context.py:362(format)
   439314    0.654    0.000    3.090    0.000 /usr/lib/python3.4/site-packages/beancount-2.0b8-py3.4-cygwin-2.4.1-x86_64.egg/beancount/core/amount.py:72(to_string)
   637535    0.424    0.000    0.424    0.000 {built-in method openssl_md5}
       17    0.395    0.023    0.643    0.038 /usr/lib/python3.4/site-packages/beancount-2.0b8-py3.4-cygwin-2.4.1-x86_64.egg/beancount/core/interpolate.py:510(compute_entry_context)
   186831    0.347    0.000    0.347    0.000 {built-in method sorted}
   439314    0.326    0.000    3.416    0.000 /usr/lib/python3.4/site-packages/beancount-2.0b8-py3.4-cygwin-2.4.1-x86_64.egg/beancount/core/amount.py:83(__str__)
   217906    0.241    0.000   21.973    0.000 /usr/lib/python3.4/site-packages/beancount-2.0b8-py3.4-cygwin-2.4.1-x86_64.egg/beancount/core/compare.py:52(hash_entry)
````

````
GET.query.stored_queries.7d44eac70d1c15ea6d29099f5f383d60.001301ms.1458588883.prof

         952188 function calls (927988 primitive calls) in 1.301 seconds

   Ordered by: internal time
   List reduced from 191 to 25 due to restriction <25>

   ncalls  tottime  percall  cumtime  percall filename:lineno(function)
37014/12814    0.594    0.000    1.273    0.000 /usr/lib/python3.4/site-packages/beancount-2.0b8-py3.4-cygwin-2.4.1-x86_64.egg/beancount/core/compare.py:18(stable_hash_namedtuple)
   227260    0.159    0.000    0.159    0.000 {built-in method isinstance}
   216570    0.092    0.000    0.092    0.000 {method 'update' of '_hashlib.HASH' objects}
    51684    0.092    0.000    0.092    0.000 {method 'format' of 'str' objects}
   216579    0.089    0.000    0.089    0.000 {method 'encode' of 'str' objects}
    37498    0.072    0.000    0.072    0.000 {method 'hexdigest' of '_hashlib.HASH' objects}
    25842    0.042    0.000    0.108    0.000 /usr/lib/python3.4/site-packages/beancount-2.0b8-py3.4-cygwin-2.4.1-x86_64.egg/beancount/core/display_context.py:362(format)
````

A couple of questions:
- (perhaps for @blais) Is that function (compare.py:18(stable_hash_namedtuple)) really important for a query/display? Can it be skipped?
- It seems like GET.query is called for each time a new custom query is picked from the list (GET.query.stored_queries, I think?), which is what is taking most of the time (23+ seconds). Is this necessary?

**Comment by yagebu** [comment]
From the profile it seems like this is something on our end after all. Still busy now, I will elaborate and probably fix this later. I assume the long page load also happens for the empty "/query/" page?

**Comment by redstreet** [comment]
>  I assume the long page load also happens for the empty "/query/" page?

Yes, correct.

**Comment by yagebu** [comment]
The slow page load should be fixed. Can you confirm?

(Note: the dropdown select for the stored queries is currently broken, will probably fix that tomorrow)

**Comment by yagebu** [comment]
> (Note: the dropdown select for the stored queries is currently broken, will probably fix that tomorrow)

Done. Easier than I thought.

**Comment by redstreet** [comment]
Much better! Both the empty query page (< 1s) and the custom queries now load fast enough (not perceptible) that it's not even worth profiling (I can't profile easily on the machine that I build). Thank you!

**Comment by blais** [comment]
On Mon, Mar 21, 2016 at 3:48 PM, Red S <notifications@github.com> wrote:

> You're right, most of the time is spent in beancount:
>
> GET.query.023268ms.1458588906.prof
>
>          17546308 function calls (17124616 primitive calls) in 23.268 seconds
>
>    Ordered by: internal time
>    List reduced from 692 to 25 due to restriction <25>
>
>    ncalls  tottime  percall  cumtime  percall filename:lineno(function)
> 629306/217906   10.412    0.000   21.732    0.000 /usr/lib/python3.4/site-packages/beancount-2.0b8-py3.4-cygwin-2.4.1-x86_64.egg/beancount/core/compare.py:18(stable_hash_namedtuple)
>   4172311    2.728    0.000    2.730    0.000 {built-in method isinstance}
>   3681951    1.668    0.000    1.668    0.000 {method 'update' of '_hashlib.HASH' objects}
>    879351    1.565    0.000    1.565    0.000 {method 'format' of 'str' objects}
>   3682835    1.416    0.000    1.416    0.000 {method 'encode' of 'str' objects}
>    637534    1.122    0.000    1.122    0.000 {method 'hexdigest' of '_hashlib.HASH' objects}
>    439314    0.873    0.000    1.993    0.000 /usr/lib/python3.4/site-packages/beancount-2.0b8-py3.4-cygwin-2.4.1-x86_64.egg/beancount/core/display_context.py:362(format)
>    439314    0.654    0.000    3.090    0.000 /usr/lib/python3.4/site-packages/beancount-2.0b8-py3.4-cygwin-2.4.1-x86_64.egg/beancount/core/amount.py:72(to_string)
>    637535    0.424    0.000    0.424    0.000 {built-in method openssl_md5}
>        17    0.395    0.023    0.643    0.038 /usr/lib/python3.4/site-packages/beancount-2.0b8-py3.4-cygwin-2.4.1-x86_64.egg/beancount/core/interpolate.py:510(compute_entry_context)
>    186831    0.347    0.000    0.347    0.000 {built-in method sorted}
>    439314    0.326    0.000    3.416    0.000 /usr/lib/python3.4/site-packages/beancount-2.0b8-py3.4-cygwin-2.4.1-x86_64.egg/beancount/core/amount.py:83(__str__)
>    217906    0.241    0.000   21.973    0.000 /usr/lib/python3.4/site-packages/beancount-2.0b8-py3.4-cygwin-2.4.1-x86_64.egg/beancount/core/compare.py:52(hash_entry)
>
> GET.query.stored_queries.7d44eac70d1c15ea6d29099f5f383d60.001301ms.1458588883.prof
>
>          952188 function calls (927988 primitive calls) in 1.301 seconds
>
>    Ordered by: internal time
>    List reduced from 191 to 25 due to restriction <25>
>
>    ncalls  tottime  percall  cumtime  percall filename:lineno(function)
> 37014/12814    0.594    0.000    1.273    0.000 /usr/lib/python3.4/site-packages/beancount-2.0b8-py3.4-cygwin-2.4.1-x86_64.egg/beancount/core/compare.py:18(stable_hash_namedtuple)
>    227260    0.159    0.000    0.159    0.000 {built-in method isinstance}
>    216570    0.092    0.000    0.092    0.000 {method 'update' of '_hashlib.HASH' objects}
>     51684    0.092    0.000    0.092    0.000 {method 'format' of 'str' objects}
>    216579    0.089    0.000    0.089    0.000 {method 'encode' of 'str' objects}
>     37498    0.072    0.000    0.072    0.000 {method 'hexdigest' of '_hashlib.HASH' objects}
>     25842    0.042    0.000    0.108    0.000 /usr/lib/python3.4/site-packages/beancount-2.0b8-py3.4-cygwin-2.4.1-x86_64.egg/beancount/core/display_context.py:362(format)
>
> A couple of questions:
>
>    - (perhaps for @blais <https://github.com/blais>) Is that function
>    (compare.py:18(stable_hash_namedtuple)) really important for a
>    query/display? Can it be skipped?
>
> I've noticed this function can be slow at times. I've considered rewriting
it in C at some point:
https://bitbucket.org/blais/beancount/src/cce57fdfca192f3f7bb443a02b25ebb356abe788/TODO?fileviewer=file-view-default#TODO-1261


AFAIK your query should only be calling it on demand if your query pulls
the "id" column:
https://bitbucket.org/blais/beancount/src/cce57fdfca192f3f7bb443a02b25ebb356abe788/src/python/beancount/query/query_env.py?at=default&fileviewer=file-view-default#query_env.py-865
It's a bit odd that it occupies so much of the running time:

**Comment by yagebu** [comment]
@blais No fault on your part! We had some horribly inefficient code in the query template. For all the stored queries, it would use the hash to determine the filename and lineno (I know it's in the meta attribute, no idea why that wasn't used). This meant linear time (in entries) for every query...

**Comment by aumayr** [comment]
> We had some horribly inefficient code in the query template.

👼🏼
