### ISSUE TITLE
Make excel related dependencies optional

### ISSUE THREAD

**Issue by yegle** [aumayr/fava#230]
I'm trying to dockerize fava and noticed the dependency on pyexcel-* caused ~22MB additional space.

Personally I never used that feature, and I could live with the CSV export if I really need it. I wonder if the dependency on them can be optional? setuptool allow `extras_require` in setup.py, and if people do want to export to .xlt file, they can install fava via `pip install fava[excel]`.

Link to the doc: https://pythonhosted.org/setuptools/setuptools.html#declaring-dependencies

**Comment by yagebu** [comment]
:+1: I also don't use the excel export and like this suggestion!

**Comment by aumayr** [comment]
Is it possible to make this optional? Meaning that when pyexcel is installed the appropriate download-links are shown, and otherwise not.

**Comment by yagebu** [comment]
Yes, we can wrap the import statement in a `try...except...` block. Will work on this.

**Comment by yegle** [comment]
Thanks @yagebu, nice trick on setting `HAVE_EXCEL`.

**Comment by aumayr** [comment]
@yagebu Looks good!

**Comment by yegle** [comment]
Care to release a new version on PyPI? I'd like to pack a new docker image to reduce image size.

**Comment by yagebu** [comment]
@yegle Sorry, forgot to reply sooner. I want to get some more features into the next release, so it might take some more time. I'm not very familiar how docker images work, but you could try building a source distribution (which will include the generated JS/CSS etc.) which you can then install with pip.
