### ISSUE TITLE
Exclude expense categories from trial balance graph?

### ISSUE THREAD

**Issue by adamgibbins** [aumayr/fava#235]
I really love the idea of the graph at the top of the trial balance page, its a great visulisation. However, tax accounts for a significant chunk of my graph meaning everything else is squashed in the corner and harder to visualise. It'd be great if there was some way to either zoom in or entirely exclude certain expense categories (e.g. Expenses:Tax) so I can get better visualisation of things actually in my control.

Thoughts?

**Comment by redstreet** [comment]
I had the same problem. A quick fix is to write a plugin to rename accounts so they get out of the Expense category:
https://github.com/redstreet/beancount_plugins_redstreet/tree/master/rename_accounts

If one can stretch principles a bit, taxes can be considered as reducing income, and thus a part of income. Of course, this is just a big hack, and it's even worse when applied to other accounts. But it's there if you want something *now* that works.

As you point out, a better way would be to simply tag expense accounts with metadata like ````fava-exclude-from-treemap````. An even better way would be to be able to this dynamically and interactively.

**Comment by adamgibbins** [comment]
@redstreet Thanks for the suggestion of moving tax to income, feels like I'm cheating myself a bit but it works well. I'm not sure I understand the point of the plugin, I just renamed my accounts with a search and replace, I can't think of some reasoning I'd want it done on the fly?

**Comment by redstreet** [comment]
Taxes don't really belong in the Income category. The point of the plugin is to avoid making a permanent change, and to instead give you the option of easily and temporarily moving taxes or any other account to different hierarchies depending on the types of treemaps you want to see in fava.

In other words, while the plugin itself is a hack, searching and replacing my source files is an even bigger hack that I would not want to do. :)

**Comment by yagebu** [comment]
I guess this issue applies to all reports with treemaps (or any chart maybe). We should have a report, probably just named "Charts", where you show the treemap for a specified list of accounts (or maybe a regular expression to filter the accounts to display). Similar for other charts. A sunburst chart (ref #198) would be an even better visualization for this kind of hierarchical data (and one of the sunburst chart examples also has some cool interactions).

**Comment by redstreet** [comment]
Perhaps a more generally useful way would be to display a treemap/sunburst of an arbitrary query assuming the output is valid to display as a treemap/sunburst.

**Comment by aumayr** [comment]
Could we achieve this with an extension to the Query view? So when the results have a certain "shape", we display charts for them?

**Comment by yagebu** [comment]
With #339 merged, the original intent of this issue is now possible using a FROM filter.

It's not clear to me if a more general way to display query result is feasible and it's a bit unrelated to the original report, so I'll close this.
