### ISSUE TITLE
IE shows apostrophe as &#39; on charts. 

### ISSUE THREAD

**Issue by miaoluda** [aumayr/fava#236]
![image](https://cloud.githubusercontent.com/assets/14816337/13945913/077dd202-f04c-11e5-806c-4fd2897651be.png)

Tested on IE10/11. 

Firefox OK. 

v0.2.5 was OK.

**Comment by aumayr** [comment]
@redstreet You run Windows, right? Does this happen for you as well?

**Comment by redstreet** [comment]
Yes, I can confirm I'm seeing this on IE11 running on Cygwin/Windows as well, in 0.2.6. I haven't checked previous versions.

I run Cygwin/Windows + Chrome. It appears fine in Chrome.

**Comment by aumayr** [comment]
@redstreet Thanks for confirming (saved me from setting up another VM). 

I think this is a bug in the [Chartist.js](https://gionkunz.github.io/chartist-js/)-library we use for the charts. I simply changed the format from `MM 'YY` (eg. `Mar '16`) to `MM YYYY` (eg. `Mar 2016`) to avoid this - and it looks cleaner anyway, IMHO.
