### ISSUE TITLE
Demo site down - 500 error

### ISSUE THREAD

**Issue by alexjj** [aumayr/fava#237]
Your [demo site](http://fava.pythonanywhere.com/) is down. I also use pythonanywhere to host my fava instance and mine has stopped working too. 

Pythonanywhere have just implemented a [deadman's switch](https://blog.pythonanywhere.com/129/) on free sites, but I've checked this on mine and the site should still be active. 

My instance also automatically updates to the latest pip version of fava, so I'm not sure if an update to fava caused the issue or it's still pythonanywhere's fault.

If you find out what is wrong could you let me know, thanks!

**Comment by aumayr** [comment]
Thanks @alexjj for reporting this. I made the mistake of not checking the demo-site after releasing the new version on Sunday, so my bad.
