### ISSUE TITLE
Show running balance when filtering out pending transactions

### ISSUE THREAD

**Issue by yegle** [aumayr/fava#238]
I just realized that when you filter out pending transactions in "Trial balance" page, the code is doing a client side javascript thing and number doesn't change in the balance column.

Would it be possible to change this behavior, and show the running balance of current listed transaction instead?

Example transaction list:

flag | amount | balance
---|---|---
* | -100 USD | -100 USD
* | -200 USD | -300 USD
! | -50 USD | -350 USD
* | -20 USD | -370 USD

Current behavior when filtering out pending trasactions

flag | amount | balance
---|---|---
* | -100 USD | -100 USD
* | -200 USD | -300 USD
* | -20 USD | -370 USD

What I'd expect

flag | amount | balance
---|---|---
* | -100 USD | -100 USD
* | -200 USD | -300 USD
* | -20 USD | -320 USD

**Comment by yagebu** [comment]
There are two different kinds of filters currently in fava:

- The ones in the header bar filter entries for all reports (and hence have an influence on both what's displayed as well as the balance etc.)
- The ones in the journal are just "display" filters that change what's shown on this page, so they shouldn't have an effect on the balance. Maybe this should be made clear on the help pages. I'm strongly against mixing these filters with the other ones, as this would increase complexity and be only helpful for one specific report.

So to have a journal with the running balance as you want, we have to make the global filters more powerful (and then you also get all other reports for your pending transactions). This will be possible when #217 is implemented, so I'll close this issue as a duplicate.
