### ISSUE TITLE
Filter type-ahead doesn't type-ahead

### ISSUE THREAD

**Issue by cgrinds** [aumayr/fava#245]
When you type into the payee filter text field, should the payee list be filtered via autocomplete as you type?
Nothing happens when I type, including when I press Enter. 
Is this a bug or a not yet implemented feature?

![image](https://cloud.githubusercontent.com/assets/242252/14068719/90dc681c-f45a-11e5-88c3-e99752183007.png)

**Comment by aumayr** [comment]
Thanks @cgrinds for the bug report - fixed in bf95e17.
