### ISSUE TITLE
Account tables are jaggy with change to flex box

### ISSUE THREAD

**Issue by cgrinds** [aumayr/fava#249]
Was the intent to make the left edge of the table jaggy?
Here's what it looks like at the latest commit (c956257) on head.

![image](https://cloud.githubusercontent.com/assets/242252/14264861/38666a18-fa8e-11e5-8d72-3a804f34e3e7.png)

Before the flex box commit, tables looked like this
![image](https://cloud.githubusercontent.com/assets/242252/14264887/615b7030-fa8e-11e5-8caa-5ca04eb6b442.png)

**Comment by yagebu** [comment]
> Was the intent to make the left edge of the table jaggy?

Yes, see #246.

**Comment by cgrinds** [comment]
Thanks @yagebu - I missed that.
