### ISSUE TITLE
Fava monitors too many files with encrypted beancount

### ISSUE THREAD

**Issue by Unode** [aumayr/fava#250]
I have my beancount file encrypted with gnupg and stored in `~/file.beancount.gpg`. I then start fava with:

    fava ~/file.beancount.gpg

As soon as I try to browse the web interface, it takes a long time to respond, my CPU spikes and some seconds later I start seeing random waiter messages on the terminal like:

    ...
    [I 160406 01:38:01 handlers:132] Browser Connected: http://localhost:5000/account/Expenses:Food/
    [I 160406 01:38:03 handlers:92] Reload 1 waiters: /home/u/.cache/mozilla/firefox/default/cache2/entries/EFFDE65F2237D8113CDD38FDBD79E0355BFFC549
    [I 160406 01:38:04 handlers:132] Browser Connected: http://localhost:5000/account/Expenses:Food/
    [I 160406 01:38:06 handlers:92] Reload 1 waiters: /home/u/.cache/mozilla/firefox/default/cache2/entries/8AE3DACD504E60795ABFCFC8F4A69FC8AFAC2CEE
    [I 160406 01:38:07 handlers:132] Browser Connected: http://localhost:5000/account/Expenses:Food/
    [I 160406 01:38:09 handlers:92] Reload 1 waiters: /home/u/.cache/mozilla/firefox/default/cache2/entries/8AE3DACD504E60795ABFCFC8F4A69FC8AFAC2CEE
    [I 160406 01:38:11 handlers:132] Browser Connected: http://localhost:5000/account/Expenses:Food/
    [I 160406 01:38:12 handlers:92] Reload 1 waiters: /home/u/.cache/mozilla/firefox/default/cache2/entries/7F60412C5A9E781A523F2DD4B0B2011172F526A9
    [I 160406 01:38:14 handlers:132] Browser Connected: http://localhost:5000/account/Expenses:Food/
    [I 160406 01:38:15 handlers:92] Reload 1 waiters: /home/u/.cache/mozilla/firefox/default/cache2/entries/8AE3DACD504E60795ABFCFC8F4A69FC8AFAC2CEE
    [I 160406 01:38:17 handlers:132] Browser Connected: http://localhost:5000/account/Expenses:Food/
    [I 160406 01:38:19 handlers:92] Reload 1 waiters: /home/u/.cache/mozilla/firefox/default/cache2/entries/7F60412C5A9E781A523F2DD4B0B2011172F526A9
    [I 160406 01:38:19 handlers:132] Browser Connected: http://localhost:5000/account/Expenses:Food/
    [I 160406 01:38:20 handlers:79] Ignore: /home/u/.cache/mozilla/firefox/default/cache2/entries/7F60412C5A9E781A523F2DD4B0B2011172F526A9
    [I 160406 01:38:22 handlers:92] Reload 1 waiters: /home/u/.cache/mozilla/firefox/default/cache2/entries/8AE3DACD504E60795ABFCFC8F4A69FC8AFAC2CEE
    ...

The web interface eventually responds but spends too long trying to monitor other files.
It seems to monitor all files in my home folder including hidden files.

If I move the beancount file to an empty folder I get:

    ...
    [I 160406 01:43:19 handlers:132] Browser Connected: http://localhost:5000/account/Expenses:Food/
    [I 160406 01:43:20 handlers:79] Ignore: /home/u/new/file.beancount.gpg
    [I 160406 01:43:21 handlers:92] Reload 1 waiters: None
    [I 160406 01:43:22 handlers:132] Browser Connected: http://localhost:5000/account/Expenses:Food/
    ...

Ans no additional file is monitored. The web interface is also a lot more responsive.
However both the `Ignore:` message and the `Reload ...: None` seems to indicate that changes to the file will be ignored as well that it's still trying to look for other files to monitor but since there's no other file in the folder, it stops.

**Comment by yagebu** [comment]
Thank you for the report! I'm not using encrypted beancount files, so I didn't run into this yet. Will investigate. For now, it's probably easiest to run `fava` in debug mode which will disable the autoreload.

**Comment by Unode** [comment]
I had a look at the cause and it seems to be a problem with `livereload` watchers.

I couldn't find documentation about this but could it be that if `server.watch` is never called, the `server.serve` code assumes all files under the current working directory (recursively) are to be monitored?

The problem with having the file encrypted is that beancount returns `filename="<string>"` (stdin pipe?) causing it to be discarded as a valid file to be monitored. I couldn't find the exact location where the filename is validated and dropped.

**Comment by yagebu** [comment]
@Unode: Sorry for only getting back to this now, running in `debug` mode seemed like a reasonable workaround to me, but now I want to properly fix this.

Unless we handle the encryption completely in Fava, it's not really possible to use the reloader functionality (as we can't decrypt the file after startup). So I'll just disable it, that should fix this.

**Comment by yagebu** [comment]
Wow - `livereload` is quite inflexible. If you don't give it any paths to watch, it always watches the current directory... So I've just made sure to add the path of the encrypted file.

This fixes the issue at hand, but support for encrypted files is still not quite bad. Feel free to open an issue with any suggestions on how to improve it.

**Comment by Unode** [comment]
I've been using the debug mode as suggested without major problems. Browsing or editing the file from the web interface doesn't work but that's a minor inconvenience since I don't do that anyway.

I tried to figure out a way to properly handle encrypted files but several parts of fava would have to be reworked. For instance a lot of code assumes that a file and therefore a filepath will be available. With encrypted files the path is not passed and only the content remains. It has been some time since I had a look but I vaguely remember that this went all the way to beancount. It handles the two differently.

As for the reloading mechanism, it's probably better to not have it at all if we are dealing with encrypted files. It might be that the first access prompts for a password and if the secret is not kept on an agent it will be requested again on next use, which would be the case when reloading the file. The prompt might happen on a TTY or via a GUI element which somewhat breaks with the server model.

I haven't looked at this in a while but last time I checked it was a considerable amount of work to implement.

**Comment by yagebu** [comment]
Thanks for the feedback.

My last fix wasn't quite perfect, it would still run the livereloader unnecessarily. I also broke the loading of encrypted files in a separate commit... Should be fixed now (83938ae). If you start `fava` on a single encrypted file, the reloader is not used at all, but if you start it on several, of which not all are encrypted then the reloader will be used.
