### ISSUE TITLE
Open pdf documents in Chrome instead of downloading

### ISSUE THREAD

**Issue by wogong** [aumayr/fava#251]
When I click a pdf document link, it will be downloaded in fava but directly opened in bean-web (my browser is Chrome).
It makes sense to have the pdf documents directly opened in Chrome instead of being downloaded.
I googled the pdf links' behaviour in Chrome and confirmed that the Chrome PDF Viewer in `chrome://plugins/` is `Always allowed to run`.
So I wonder it may be because the links' difference between fava and bean-web.
- fava: `<a href="/document/?file_path=%2Fhome%2Fwogong%2Fbc%2FLiabilities%2FCreditCard%2F2016-04-05.2016-04.pdf">2016-04-05.2016-04.pdf</a>`
- bean-web: `<a href="/view/year/2016/doc/home/wogong/bc/Liabilities/CreditCard//2016-04-05.2016-04.pdf" class="filename">2016-04-05.2016-04.pdf</a>`

Any ideas?
Thanks in advance.

**Comment by corani** [comment]
It is because of https://github.com/aumayr/fava/blob/master/fava/application.py#L179

**Comment by yagebu** [comment]
fava should behave like this since 40a16e7ec04ebfc33183f60201fe0ed64bd04473 (which is part of the latest release). Which version are you running?

> It is because of https://github.com/aumayr/fava/blob/master/fava/application.py#L179

No, that's for query results, which we want to send as attachments. [This](https://github.com/aumayr/fava/blob/master/fava/application.py#L110) is the relevant line.

**Comment by wogong** [comment]
@yagebu 
cool! Things works well now after upgrading to version 0.2.6.
previous my beancount-fava version is 0.2.5.

Thanks @corani.

**Comment by corani** [comment]
Ah, you're right @yagebu. Thanks for the clarification. And now that you
mention it, I do remember that change going in... I'm a bit fuzzy lately :-)

On Thu, Apr 7, 2016 at 10:34 PM, Cheng Zhen <notifications@github.com>
wrote:

> @yagebu <https://github.com/yagebu>
> cool! Things works well now after upgrading to version 0.2.6.
> previous my beancount-fava version is 0.2.5.
>
> Thanks @corani <https://github.com/corani>.
>
> —
> You are receiving this because you were mentioned.
> Reply to this email directly or view it on GitHub
> <https://github.com/aumayr/fava/issues/251#issuecomment-206933672>
>



-- 
Best regards,
Daniël Bos


Your government is reading your email. Slow them down with encryption.

My public key: http://goo.gl/gms497 (4096 bit RSA, id EF2D5D91)
Fingerprint  : D8D0 9FBE F075 F709 7B52  2F73 326C 2123 EF2D 5D91
