### ISSUE TITLE
Bar chart: Increase clickable area for small bars

### ISSUE THREAD

**Issue by yegle** [aumayr/fava#253]
Currently there's no minimal length of the bars in bar charts, which may result in a chart like below, where I can barely see the amount of the last bar.

![screen shot 2016-04-07 at 5 58 42 pm](https://cloud.githubusercontent.com/assets/146133/14371229/6add6420-fcea-11e5-9a39-83ed834fb899.png)

**Comment by yagebu** [comment]
I don't really see the issue here. Isn't it the point of a bar chart to show how much is in the account? So if the amount is small (or 0) then the bar should also be small (or of height 0).

**Comment by yegle** [comment]
In a printed bar chart, yes. But on a computer screen a bar too short will make it unclickable.

**Comment by yagebu** [comment]
I see what you mean. Increasing the bar doesn't make sense but we can increase of the clickable area.

**Comment by yagebu** [comment]
As I'm planning to rewrite the bar and line charts on top of d3, I won't make any changes to the current charts. The new charts should include this.
