### ISSUE TITLE
Events table missing events

### ISSUE THREAD

**Issue by xiaoruoruo** [aumayr/fava#254]
It seems /events/ only display the last event in the table.

Example file:

2014-04-15 event "employer" "A"
2015-03-15 event "employer" "B"
2016-03-15 event "employer" "C"

Attached screenshot for http://localhost:5000/events/
![screenshot](https://cloud.githubusercontent.com/assets/452520/14374508/6d4b8de2-fd0b-11e5-88a2-2f9bc7d55e16.png)

**Comment by yagebu** [comment]
That's the intended behaviour. Click on the event name to show the page for the event employer.
