### ISSUE TITLE
Improve investment display in Journal table

### ISSUE THREAD

**Issue by cgrinds** [aumayr/fava#255]
Today investments display like so:
![image](https://cloud.githubusercontent.com/assets/242252/14387330/e7909a82-fd76-11e5-9acb-e3ec080caa61.png)

Wouldn't it be more clear to display the posting like so?
![image](https://cloud.githubusercontent.com/assets/242252/14387491/ab4e8812-fd77-11e5-91a5-9854233ad180.png)

Fewer decimals would help too, but that's a slightly separate issue.

**Comment by yagebu** [comment]
Now the cost is rendered just like it can be specified inside `{`,`}` in the beancount file. I don't think your suggestion would really work as a posting might have both price and cost. Also, I think the journal should be as close to the beancount file as possible (in terms of precision and what it displays).

**Comment by cgrinds** [comment]
@yagebu looks good. My suggestion was more about showing the cost.number instead of the cost string representation. This address that - thanks.
