### ISSUE TITLE
Release 0.3.0

### ISSUE THREAD

**Issue by aumayr** [aumayr/fava#263]
@yagebu What do you think about releasing 0.2.7 when #257 and #259 are done? Any pressing open issues that have to go into this release?

**Comment by yagebu** [comment]
I think we've got enough new features for a new minor release (0.3.0).

I'll also try to fix #191 before, it's been open for ages and shouldn't be hard to fix.

**Comment by aumayr** [comment]
I'll leave this issue open to discuss the release.

**Comment by aumayr** [comment]
I have a feeling that #257 will be hard to merge, as I created the branch long ago and `master` changed quite a bit…

**Comment by yagebu** [comment]
@aumayr: I can have a go at it if you want. I've done uglier merges/rebases ;)

Might get some time tomorrow or if not I can definitely do it on the weekend. Will also try to get #259 merged then.

**Comment by aumayr** [comment]
Awesome, thanks! 

I'm not very comfortable with large merges/rebases, as I have no real experience with them (outside fava)…

**Comment by aumayr** [comment]
@yagebu I think there is nothing in the way of releasing a new version. Do you agree?

**Comment by yagebu** [comment]
Yes!

**Comment by aumayr** [comment]
Can you have a go at the changelog again? I will then upload to PyPI, push a new version to Github Pages and update the Demo on pythonanywhere.

**Comment by yagebu** [comment]
> Can you have a go at the changelog again?

I won't have any time to do it until Wednesday. If you could do it before then, that'd be cool, otherwise I'll do it then.

**Comment by aumayr** [comment]
> If you could do it before then, that'd be cool, otherwise I'll do it then.

No problem, I'll have a go at it.

**Comment by aumayr** [comment]
My first try: b3b1402

I'm not quite happy with the language, but maybe this will get better next time :-) Please give a 👍 if you think it's ready to get published.

**Comment by yegle** [comment]
Could you link to the help page of budget functionality? I can't seem to find it anywhere.

**Comment by adamgibbins** [comment]
@yegle https://github.com/aumayr/fava/blob/master/fava/docs/budgets.md

**Comment by yagebu** [comment]
> My first try: b3b1402

👍 

(Since the changelog is only on the website anyway, we can always improve it after we make a release)

**Comment by aumayr** [comment]
Done and out in the wild. 

- [X] PyPI-release
- [X] Github release
- [X] fava.pythonanywhere.com updated
- [X] aumayr.github.io/fava updated
- [X] Post on the Beancount mailing list

Thanks everyone, especially @yagebu, for all the help! 

Up to the next one…
