### ISSUE TITLE
Hodings page: show one row for accounts with BookingMethod=NONE

### ISSUE THREAD

**Issue by yegle** [aumayr/fava#264]
For accounts with booking method `NONE` (reference https://docs.google.com/document/d/1wAMVrKIA2qtRGmoVDSUBJGmYZSygUaR0uOMW1GV3YE0/edit#heading=h.omdgvaikswd0), it should not list holdings separately.

Currently it seems like each transaction that involves an account with BookingMethod=NONE, a separate row will be listed on the Holdings page.

E.g. with the following example, the Holdings page should only list one line showing
```
2016-01-01 open Assets:MyStock STOCK "NONE"
2016-01-01 open Equity:Opening-Balance USD
2016-01-02 *
    Assets:MyStock 1 STOCK {10 USD}
    Equity:Opening-Balance
2016-01-03 *
    Assets:MyStock 1 STOCK {20 USD}
    Equity:Opening-Balance
2016-01-04 *
    Assets:MyStock -1 STOCK {11 USD}
    Equity:Opening-Balance
```
The holdings page should only contain one line.

**Comment by yagebu** [comment]
All lots in the account have a different cost, so they should be listed separately in the holdings table. If you want them group, you can select "Holdings by Currency". I don't really know what you'd expect to see here?

**Comment by yegle** [comment]
The NONE booking method is for accounts like 401k (US retirement investment account). Since these are tax advantage account, you pay tax on whole withdraw amount (things may differ for different kind of 401k), there's no point tracking the lot information.

The NONE booking method is to say: I don't care about the lot information. When I sell, calculate the average cost and use that as my cost basis. When I buy, re-calculate my cost basis with the latest price.

Holdings by Currency doesn't solve my problem since I have normal investment account which I do track lot informations.

**Comment by yagebu** [comment]
> The NONE booking method is to say: I don't care about the lot information. When I sell, calculate the average cost and use that as my cost basis.

No, "NONE" means "no booking" and not "average cost booking". There's ongoing work by Martin Blais to implement more booking methods. (see also [Proposal - Inventory Booking Improvements](http://furius.ca/beancount/doc/proposal-booking))
