### ISSUE TITLE
Remove "Equity" charts

### ISSUE THREAD

**Issue by corani** [aumayr/fava#266]
Since the `Equity` treemap and sunburst charts show only "Opening Balances", they provide no useful information. Removing them would clean up the chart picker somewhat (from 15 to 11 for me)

**Comment by yagebu** [comment]
Ref the discussion in #267

**Comment by cgrinds** [comment]
I don't understand what a closing_balance is, but after this change the treemap and sunburst show no data. Treemap shows "Chart is empty" when I go to page `http://127.0.0.1:5000/income_statement/?interval=month` and click on `Expenses (USD)`

I did a
```
make clean
make build-js
pip install --editable .
```

I tried with my leger file (which showed charts before commit: d38334a2607addef6b70aef0ae1779ae33ec0af5) and a bean-example created one. Same empty data in both cases.

**Comment by yagebu** [comment]
@cgrinds: Thank you for pointing out this mistake! "Closing" generates conversion entries such that all accounts sum up to zero. Additionally, it moves all income and expenses to an equity account. I forgot about the second, which emptied the income and expenses charts.

I've reverted the commit. I guess they should really only be used on the balance sheet.
