### ISSUE TITLE
Unable to execute custom queries when the query drop down is not blank

### ISSUE THREAD

**Issue by redstreet** [aumayr/fava#270]
Using 86dbbe6c74. If a custom query is selected, updates/modifications to the query line in the text box is ignored. Instead, the selected custom query is always executed.

For example, if I:
1) pick a custom query from the drop down menu
2) execute it
3) modify that query in the text box, or even type a brand new query into the text box at this point

then I'm unable to execute the newly typed or modified query. Instead, the query selected in the text box replaces my changes and executes.

**Comment by yagebu** [comment]
Can't reproduce. Can you tell us the last commit that worked for you? There haven't been any changes recently that should influence the behaviour of this form. Any errors in the JS console? What browser are you using? Did you run `make`?

**Comment by redstreet** [comment]
I'm unable to reproduce it either, after installing from a freshly cloned repo. Not sure where this behavior came from. Sorry if I made you hunt! I'll close this issue.
