### ISSUE TITLE
Chart location: sunburst vs treemap

### ISSUE THREAD

**Issue by redstreet** [aumayr/fava#274]
Uses might predominantly prefer one of treemaps or sunburst over the other. So I wonder if it makes sense, just to reduce clutter, to restore the "tabs" from:

"Income | Expenses | Expenses (Sunburst) | Income (Sunburst)"
to just
"Income | Expenses"

and add an extra line above it that shows up only when charts are being displayed that allows switching from sunburst to treemap and back. Whether sunbursts or treemaps are displayed by default can be a configurable option.

This is just a  minor suggestion, so please feel free to ignore/close.

**Comment by yagebu** [comment]
Good suggestion, this is something I also had planned. Low-priority for me though, so if anyone else wants to have go at this, feel free.
