### ISSUE TITLE
Color scheme for better representation of treemap hierarchies.

### ISSUE THREAD

**Issue by redstreet** [aumayr/fava#275]
Separating out a thread from #198. To clarify one of the things I was talking about there, see:

![image](https://cloud.githubusercontent.com/assets/691755/14943775/a4ea335a-0f96-11e6-82d5-7e83dcc01882.png)

vs

![image](https://cloud.githubusercontent.com/assets/691755/14943779/c16a0d7a-0f96-11e6-9a72-16d1f9203d59.png)

The bottom image makes the hierarchy clearer: one can see that there are 3 major rectangles, and then several sub-rectangles. Since visualizing the hierarchy is very useful, there are a few ways to do this:
- add a thicker border like the above. This only makes perhaps 2 or 3 levels of hierarchy distinguishable
- color scheme: in the above, the three main rectangles happen to be three different expense categories at the same hierarchy level. So it would be best if they were represented by three entirely different colors. But they aren't. So the chart is a bit confusing.

Thinking about it more, tweaking the color scheme would be the better way to go. If this is non-trivial to fix, please feel free to send me a pointer to the code, and I can look at it at some point. Thanks!

**Comment by yagebu** [comment]
> Thinking about it more, tweaking the color scheme would be the better way to go. If this is non-trivial to fix, please feel free to send me a pointer to the code, and I can look at it at some point. Thanks!

We use currently d3's [20c](https://github.com/mbostock/d3/wiki/Ordinal-Scales#category20c) which has a lot of similar colors (I guess it looked best for my treemaps when I implemented them). You could try the other scales (or find some even nicer color scales if you want). It's the `treemapColorScale` defined somewhere at the top of `charts.js`.

**Comment by redstreet** [comment]
Thanks. I just took a look and this might be a bit tricky because it makes sense for siblings to have similar colors (which d3's 20c enables in groups of 4), but top-level siblings might be better off not having similar colors.

I'll play around with the colors and the code that applies them for a while and get back.

**Comment by redstreet** [comment]
Here's what I found:
- for categorical data, we want to use a non-sequential color set to distinguish categories from one another. d3's 20c happens to be a sequential color set (5 colors in sets of 4 each), which is what is causing the problem. [d3's 10](https://github.com/mbostock/d3/wiki/Ordinal-Scales#category10) is non-sequential and works well functionally, but the colors are too bold and uncomfortable IMHO.

The [Cynthia Brewer ColorBrewer](http://colorbrewer2.org) set has several sets specifically for categorical data. Quoting from that website:

> 3. Qualitative schemes do not imply magnitude differences between legend classes, and hues are used to create the primary visual differences between classes. Qualitative schemes are best suited to representing nominal or categorical data.

I don't know what the licensing is on that, and how to use them, but d3 seems to say [they are bundled](https://github.com/mbostock/d3/wiki/Ordinal-Scales). If they are easy to switch to, this is what I recommend:

"8-class Accent, qualitative data"  (preview: go [http://colorbrewer2.org/](here), choose 8, qualitative, uncheck 'borders'). If at all easy, it would be nice to remove the "hot pink" color alone from that set, just so it doesn't dominate.
