### ISSUE TITLE
Selected month is off by one

### ISSUE THREAD

**Issue by redstreet** [aumayr/fava#276]
If I type "April 2016" into the time search, the address changes correctly to "?time=April+2016". However, Monthly Expenses and Monthly Income show March 2016.

**Comment by yagebu** [comment]
I can't reproduce this. Is this on `master` or the last release?

**Comment by redstreet** [comment]
I'm running from 567166.

**Comment by cgrinds** [comment]
I'm on master and see the same - when I'm on the Income statement page. `income_statement/?time=May+2016` I see the following
![image](https://cloud.githubusercontent.com/assets/242252/15054833/68c085d4-12d7-11e6-83ad-d64c3c66ddbb.png)

**Comment by yagebu** [comment]
That's quite odd, can you check the source and look for the corresponding chart data, it should look like the following:

    window.chartData.push({"date_format": "MMM YYYY", "interval_totals": [{"begin_date": "2016-05-01", "totals": {"EUR": 35.20}}], "label": "Monthly Net Profit", "type": "bar"})

If that shows the wrong date for you, I don't really understand why I can't reproduce this. Can you give more details how you installed it?

**Comment by cgrinds** [comment]
@yagebu I installed fava from source. Just now, I cloned into a new directory, created a new bean-example file (seed 1), and recreated the problem.

And yes, I see the chart data, but the chart says April 2016, just like the screenshot above.
```
Request made: http://127.0.0.1:5000/example-beancount-file/income_statement/?time=May+2016

    <script>window.chartData.push({"date_format": "MMM YYYY", "interval_totals": [{"begin_date": "2016-05-01", "totals": {"IRAUSD": 1200.00, "USD": -2870.86, "VACHR": -5}}], "label": "Monthly Net Profit", "type": "bar"})</script>


    <script>window.chartData.push({"date_format": "MMM YYYY", "interval_totals": [{"begin_date": "2016-05-01", "totals": {"USD": -5239.70, "VACHR": -5}}], "label": "Monthly Income", "type": "bar"})</script>


    <script>window.chartData.push({"date_format": "MMM YYYY", "interval_totals": [{"begin_date": "2016-05-01", "totals": {"IRAUSD": 1200.00, "USD": 2368.84}}], "label": "Monthly Expenses", "type": "bar"})</script>

```

**Comment by yagebu** [comment]
This seems to be a timezone problem. I assume you're in some timezone behind UTC, right? When Javascript parses the date, it assumes it to be in UTC, but it outputs it in your local time (so instead of `2016-05-01 00:00 -> May 2016`, you get something in April). Will provide a fix soon.

**Comment by cgrinds** [comment]
Yes, EDT.

**Comment by xentac** [comment]
Oh wow, this is actually more insidious than I originally thought.

The graph columns are off by 1 for the month (currently it's 2016-05-08 and my year to date columns are Dec 2015 -> Apr 2016).  Clicking on them filters to the wrong month (!): clicking on the data representing May 2016 with the label of Apr 2016 sets the filter to 2016-04, displays 2016-04 data, but gives it a label of Mar 2016.

I thought I'd be able to just do the translation in my head, but turns out I really really can't.

**Comment by cgrinds** [comment]
Thanks @yagebu works for me.

**Comment by broven** [comment]
month filter has disable in lateest code? I trie to implement this, found this issue, and i try `income_statement/?time=May+2021` it report Failed to parse date: May 2021
