### ISSUE TITLE
Time axis labels

### ISSUE THREAD

**Issue by redstreet** [aumayr/fava#277]
"January" is not showing up in the time axis lables. See below. The ideal label might contain month+year for January ("January 2015"), and just the month for the remaining.

![image](https://cloud.githubusercontent.com/assets/691755/14970695/126189da-1080-11e6-89cd-f2b312f3e68b.png)

If this was a deliberate decision, the simplicity of having just the year is nice, but it continues to trip me up as I read the plots. Anyway, it's a minor concern, so please feel free to close if you prefer it the way it is.

**Comment by aumayr** [comment]
I quite like how this is rendered, although I completely understand that it is irritating first.

**Comment by yagebu** [comment]
This is the default behaviour of the d3 time axis, and I quite like it this way.
