### ISSUE TITLE
Please make clicking on the filters labels not clear them

### ISSUE THREAD

**Issue by xentac** [aumayr/fava#288]
50% of the time I click accidentally just to open the menu and instead I clear my filters.  In addition, this makes it harder to use on an android phone (you have to hold till a menu comes up then click out of the menu).

I would really prefer it if there was a button at the top of the list to clear the filter and clicking only opened the menu (in addition to the mouseover so that we support both mouse and touch).

**Comment by aumayr** [comment]
I can see the problem, and an obvious solution (as you suggested):

See PR #290 for a draft and a screenshot.
