### ISSUE TITLE
Compatibility with PyInstaller 

### ISSUE THREAD

**Issue by gambhiro** [aumayr/fava#291]
Many thanks for this awesome tool, accounting never looked so good!

I would like to build a windows executable with PyInstaller for the *other* people in the office. [This article](http://sparkandshine.net/en/build-a-windows-executable-from-python-scripts-on-linux/) has got me started, but I realized I don't know enough about python applications.

Could you give some hints on how one would package fava with PyInstaller?

`make` succeeds to install the `npm` modules and create the build folder. In there, which .py should I run PyInstaller on?

**Comment by yegle** [comment]
If you are installing from source (e.g. from github clone), you'll need npm to build the css/js files. You don't need those if you install from pypi.

**Comment by yagebu** [comment]
I've not used PyInstaller before so I'm not familiar with how it works. We rely on some files (the default settings, and all the templates, css, etc.) to be available in the same folder as the `fava` module. So we have to tell PyInstaller to include those files. Possibly the way we discover those files will also have to be adjusted.

To get started, add the following to `fava/cli.py`, and run PyInstaller on it:

    if __name__ == '__main__':
        main()

If you run the script that PyInstaller generates for it, you'll immediately get some errors because it can't find the default settings. If you can tell PyInstaller to include the files, you might be able to get it running.

**Comment by gambhiro** [comment]
Thanks, sounds like a good start!

**Comment by aumayr** [comment]
@gambhiro Ever thought of using [Electron](http://electron.atom.io) to package fava? Are you interested in this?

**Comment by gambhiro** [comment]
@aumayr That would be impressive. The front-end could work as it is. But how would the back-end talk to beancount?

**Comment by aumayr** [comment]
I actually have this already running:

- Electron starts a python-proces with fava in the background when the application is started.
- The UI works as usual, and I added some CSS-modifications that adapt it to a chromeless window. 
- When the application is quit, the python-process is stopped. 

Currently there are two "problems":
1. fava has to be installed systemwide first, as I have not figured out yet how to "package" it with the Electron application.
2. When you click a link in fava to switch the view (eg. from the Income Statement to the Balance Sheet), the screen flicks white for a couple of milliseconds until the page is loaded. This does not look very nice to my eyes.

**Comment by gambhiro** [comment]
Is this https://github.com/aumayr/fava-electron ?

For 1., it sounds to me you can just ask the user to run two installers -- one that installs fava as a compiled binary in their PATH, and another that installs the Electron interface.

It is hard to get Windows users be able to think in terms of commands in a shell, but if they have some icon to click or drag things onto, it starts to be part of the world.

**Comment by aumayr** [comment]
Yes it is, but I think I didn't push to that repo for a couple of commits… will see how far my local version and that repo are apart from each other. 

Two installers sounds OK as well, though one would be nice.

**Comment by gambhiro** [comment]
On the 2. bug you mentioned, that description sounds like it could be an async event bug. Say, when the user opens a new view, then I suppose there are requests to the back-end, and the flicker could be happening when those requests return with their callbacks and the DOM is updated.

Are you using promises? https://github.com/kriskowal/q is a neat library

**Comment by gambhiro** [comment]
He is describing a similar use case (electron with a python app):

https://www.fyears.org/2015/06/electron-as-gui-of-python-apps.html

**Comment by aumayr** [comment]
@gambhiro I finally pushed the new changes, sorry for the delay:

https://github.com/aumayr/fava-electron/commit/7c8eb3cd560521794a190a28d8acc03d0a41dcff

Looks like this on my Mac:

![screenshot](https://cloud.githubusercontent.com/assets/5135450/15555512/588004ea-22c9-11e6-90ec-d4d657890e95.png)

This is very basic, but works for me. Some notes:

- Upon first start, a File-Chooser-Dialog is opened so you can choose which Beancount-file to use.
- Runs `fava` on port `8889`.

If you are further interested in this, we can discuss it over at the `fava-electron`-repo: [aumayr/fava-electron](https://github.com/aumayr/fava-electron)

**Comment by yagebu** [comment]
I've added support for compiling fava with PyInstaller. Simply run `make pyinstaller` (in a virtualenv where pyinstaller and fava's dependencies are installed). This will produce a binary at `dist/fava`.

**Comment by gambhiro** [comment]
Hm, on Linux pyinstaller succeeds, but I keep getting no module errors.

```
cd fava
virtualenv -p python3 venv
. venv/bin/activate
make pyinstaller
./dist/fava
Traceback (most recent call last):
  File "fava/cli.py", line 5, in <module>
ImportError: No module named 'click'
Failed to execute script cli
```

Then (still in the venv) I have `pip3 install click`, and in a new shell:

```
virtualenv -p python3 venv
. venv/bin/activate
make pyinstaller
```

Succeeds, but now misses flask. I repeated the above and it moved on to flask_babel.

I'm not experienced with the python tools, does this indicate a missing path variable or something along those lines?

**Comment by aumayr** [comment]
In the virtualenv, you first have to install all the Python dependencies fava has. 

This is as easy as running `pip3 install -e .`, which installs fava and all it's dependencies in the current virtualenv.

**Comment by gambhiro** [comment]
Thank you, that worked great. I will have to try to get a Windows binary as well.
