### ISSUE TITLE
Holdings by account shows zeroed accounts

### ISSUE THREAD

**Issue by cgrinds** [aumayr/fava#292]
Holdings by account shows accounts that have nothing in them. Is this similar to the issue @aumayr ran into [here](https://github.com/aumayr/fava/pull/257#commitcomment-17333317)?

For example - with the following transactions I see
![image](https://cloud.githubusercontent.com/assets/242252/15269632/27f3ada8-19d3-11e6-9672-c5ecb50434a8.png)

I expected it to be removed from the **Holdings by account** table or maybe I'm misunderstanding how the table works.

If I try to close the account (figuring that might remove it), beancount complains that `Unopened account Assets:XYZ is being closed`

```
2015-12-31 open Assets:XYZ
2015-12-31 open Assets:XYZ:Stock:XYZ 

2015-12-31 * "Opening Balance for XYZ"
  Assets:XYZ 29,739.86 USD
  Equity:Opening-Balances

2016-01-09 * "Buy XYZ FUND" 
  Assets:XYZ:Stock:XYZ 3123.935 XYZ {9.52 USD}
  Assets:XYZ

2016-02-02 * "SellTransfer XYZ FUND" "emptied account; these are proceeds"
  Assets:XYZ:Stock:XYZ -3,123.935 XYZ {9.52 USD} @ 9.55921 USD
  Assets:Bank:Checking:Joint
```

**Comment by yagebu** [comment]
I guess this is due to rounding, in which case I would call this the correct behaviour.

(also, the behaviour is consistent with what `bean-web` shows)

**Comment by cgrinds** [comment]
Thanks @yagebu - you're right, bean-web does the same.
I don't understand why rounding is a factor though, since there are zero assets left, regardless of price.

@blais does this look right to you? If not I'll open a beancount issue.

**Comment by blais** [comment]
https://bitbucket.org/blais/beancount/issues/36/balances-output-sometimes-outputs-000
https://bitbucket.org/blais/beancount/src/674041385e357944133f7aefeac4126f168c14a5/TODO?fileviewer=file-view-default#TODO-4423

**Comment by yagebu** [comment]
> I don't understand why rounding is a factor though, since there are zero assets left, regardless of price.

`Assets:XYZ:Stock:XYZ` is empty (and not shown on the Holdings page), but `Assets:XYZ` still contains -0.0012 USD (as 3123.935*9.52 = 29739.8612).

**Comment by cgrinds** [comment]
Thanks @yagebu and @blais.  Got it - the problem is not the sell, but the buy that leaves -0.00120 USD in `Assets:XYZ`
