### ISSUE TITLE
Also show open/close/balance directives when account filter is active

### ISSUE THREAD

**Issue by pfrancois** [aumayr/fava#293]
in fava version 2.6
when i select a account in the filter of the general journal, i can't see anymore the special directive;
in particular, i can't see the balance directive for this account.

**Comment by yagebu** [comment]
All filters but the time filter only filter for transactions currently. If you want to view the journal for one account, you can click on the account name.

**Comment by aumayr** [comment]
@yagebu Should we change this behavior ("All filters but the time filter only filter for transactions currently")?

**Comment by pfrancois** [comment]
yes if it is possible. it will be good if it is not complicated
