### ISSUE TITLE
Display transaction for account with long history

### ISSUE THREAD

**Issue by yegle** [aumayr/fava#295]
I have some account with history back to 2013 and the journal is long enough that it takes too long to scroll to the end of page for checking the latest transactions.

The most simple way would be an option to display transactions in reverse order, that will solve my problem but may seem strange.

A better way would be an option to only show transactions between (-N, N) months relative to current date, and user can move the window forward/backward somewhat.

**Comment by yagebu** [comment]
This is possible with the time filter. If you just want to check the most recent transactions, you could filter by `last month - this month` for example.

**Comment by yegle** [comment]
@yagebu 
Yes filter by `last month - this month` works (didn't know I can specify a range in the filter).

I think it's reasonable to persist the time filter in cookie and use the same filter when the filter is not present in query string.

**Comment by aumayr** [comment]
I'm strictly against using cookies. fava should stay "stateless", meaning that the URL-query-part should hold all the info for rendering the page. Introducing cookies would be against that, and make everything about fava more complicated and "unpredictable". 

You can use the `custom-links`-setting to add custom links to the sidebar (containing the time-filter).
