### ISSUE TITLE
error 500 on opening an entry source

### ISSUE THREAD

**Issue by gambhiro** [aumayr/fava#298]
I'm using v0.3.0. When I see a list of entries, say, in the Journal view, and click on the date to open the beancount source, the server process errors out with 500.

Opening the Source view for the main beancount file works.

It may be the `include`. I have an `include` directive in the main beancount file, which also calls `include` for other beancount files.

Before, fava followed the successive includes, opened the source view, and saved back to the correct file.

**Comment by aumayr** [comment]
Thanks @gambhiro for reporting this - still don't know why this was not caught in our automated tests.

Anyhow: I found the bug, and fixed it.

**Comment by gambhiro** [comment]
Excellent, it works now.
