### ISSUE TITLE
Title without a English character leads to redirecting problem (v0.3.0)

### ISSUE THREAD

**Issue by miaoluda** [aumayr/fava#301]
Maybe it cannot get a valid url if there is not any English character or number in the title.  

Regular:
`option "title" "Example Beancount file"`
![default](https://cloud.githubusercontent.com/assets/14816337/15606693/6b9e055e-2440-11e6-89a8-7b6a87471aa6.png)

Test case 1 :
`option "title" "ナαնа 烫烫烫"`
Test case 2 :
`option "title" "%"`
![image](https://cloud.githubusercontent.com/assets/14816337/15610538/55936188-2458-11e6-9c34-6dfcc35802a7.png)

Test case 3:
`option "title" "Example Beancount file \"`

![image](https://cloud.githubusercontent.com/assets/14816337/15606415/a91c947e-243e-11e6-919b-9766f07b134e.png)

V0.2.6 OK 
![image](https://cloud.githubusercontent.com/assets/14816337/15611613/c4a70944-245d-11e6-9f67-e2b6e66b29dd.png)

**Comment by yagebu** [comment]
We now keep unicode characters in the URL. They will be escaped but modern browsers will display them normally. And in case the title only contains non-word characters, we fall back to the file path (which will lead to ugly URLs but should not crash fava)

Does this work for you?

**Comment by miaoluda** [comment]
Redirecting problem is solved. Thank you. 

I case of a non-word title, the URL would be too ugly if the file path is deep. What about just a file name?

**Comment by yagebu** [comment]
> I case of a non-word title, the URL would be too ugly if the file path is deep.

I don't really think that a non-word title is something we need to support well. Making the URL ugly might encourage you to set a better title ;)
