### ISSUE TITLE
Chart enhancements

### ISSUE THREAD

**Issue by corani** [aumayr/fava#304]
1. I suggest to move the chart picker (currently links below the chart) into a select box, next to the interval selector above the charts. This accomplishes two goals:
  - Make the interface _less busy_ (especially if you have multiple operating currencies).
  - Make the interface _more consistent_.
2. Move the legend outside of the chart. It's currently overlapping the line charts in many cases. Since we're using almost the entire screen width, I don't think we'd loose much of the chart area.

![screenshot from 2016-05-28 18 23 44](https://cloud.githubusercontent.com/assets/480775/15626844/552b715e-2502-11e6-9a5b-289c1a798f69.png)

**Comment by yagebu** [comment]
Thank you for opening an issue on this.

1. I agree that this needs fixing but I'd rather keep the chart picker. To make it less busy, I think we should move the currencies to a select. Then there'd be only a fixed (and small) number of labels we need to display (those we could move to the top of the chart, maybe style them like tabs).

2. Moving the legend outside of the chart seems like a good idea. I'd prefer to move it to the bottom or top.

**Comment by corani** [comment]
Another suggestion:

3. When there are no sub-accounts (e.g. in trial balance), don't show treemap or sunburst, as they'll be meaningless.
