### ISSUE TITLE
Create Gitter channel

### ISSUE THREAD

**Issue by corani** [aumayr/fava#306]
Some discussion is better done through slow-chat than through Github issues. [Gitter](https://gitter.im/) seems to work quite nicely, with a pretty web UI and apps for various mobile platforms, integration with Github, and I'm already using it for some other projects.

What are your thoughts?

**Comment by aumayr** [comment]
I personally have never used Gitter, but I have seen the link to it on many other Github projects. 

I think we can give it a go, as it is free and you are absolutely right that some discussion would be better to have in a chat than in Github issues. 

So I'll add a link to it and let's see how this works :-)
