### ISSUE TITLE
Unable to scroll sidebar

### ISSUE THREAD

**Issue by adamgibbins** [aumayr/fava#308]
Running latest master branch I'm unable to see the bottom of the sidebar unless I zoom out to 90% in Chrome. There's simply no way to scroll it, it doesn't move with the rest of the page.

**Comment by aumayr** [comment]
In `master` the sidebar (and header) have been changed to be fixed, not scrolling with the content. 

How high is your browser window? Can you post a screenshot?

**Comment by adamgibbins** [comment]
I'm running a Macbook Retina 13" at 1440x900:
<img width="1440" alt="2016-05-31_zhyyakf8fv" src="https://cloud.githubusercontent.com/assets/46830/15668432/1b1293c2-2713-11e6-9a2c-09a88c73c43e.png">

If I zoom out to 90% (personally I actually find this a better fit, doesn't bother me running like this at all, I find the spacing better etc):
<img width="1440" alt="2016-05-31_i9t2nktwh4" src="https://cloud.githubusercontent.com/assets/46830/15668465/4bc45640-2713-11e6-8f9e-988fdfb92a74.png">

**Comment by aumayr** [comment]
Actually I just realized I have the same issue on my MacBook Air 13", where (with just one custom link in the sidebar) the sidebar is too high for the window.

I'll fix this in CSS.

**Comment by aumayr** [comment]
This is tricky. I can make the sidebar scrollable if there is too much content, but you have to explicitly move the mouse over the sidebar and then scroll. The browser does (at least for me) not show a scrollbar, but it is there if you scroll. 

The main problem is that "Errors" are at the very bottom of the sidebar, so if you make a mistake in your Source file, this is not obvious until you scroll the sidebar, which is annoying.

So I have the following suggestions:

1. Move the error-idicator to a bubble next to the "Source"-menu-item or to it's own item below "Source" (as it was before, but hide it if there are no errors).
2. Remove "Documents" and "Notes" from the sidebar. 

What do you think @adamgibbins? /cc @yagebu

**Comment by corani** [comment]
I don't think removing sections from the sidebar is a good idea: If you
then add a few more custom links, you'd run into the same problem again.

In, for example, gmail, they've solved this problem in the same way as your
first suggestion: the sidebar is scrollable, but you have to explicitly
move the mouse over it (at which time it'll show a scrollbar).

As an aside, I believe it should be possible to always show the scrollbar
on a div, though apparently some Mac versions need specific hacks for this.

On Tue, May 31, 2016 at 9:34 PM, Dominik Aumayr <notifications@github.com>
wrote:

> This is tricky. I can make the sidebar scrollable if there is too much
> content, but you have to explicitly move the mouse over the sidebar and
> then scroll. The browser does (at least for me) not show a scrollbar, but
> it is there if you scroll.
>
> The main problem is that "Errors" are at the very bottom of the sidebar,
> so if you make a mistake in your Source file, this is not obvious until you
> scroll the sidebar, which is annoying.
>
> So I have the following suggestions:
>
>    1. Move the error-idicator to a bubble next to the "Source"-menu-item
>    or to it's own item below "Source" (as it was before, but hide it if there
>    are no errors).
>    2. Remove "Documents" and "Notes" from the sidebar.
>
> What do you think @adamgibbins <https://github.com/adamgibbins>? /cc
> @yagebu <https://github.com/yagebu>
>
> —
> You are receiving this because you are subscribed to this thread.
> Reply to this email directly, view it on GitHub
> <https://github.com/aumayr/fava/issues/308#issuecomment-222689495>, or mute
> the thread
> <https://github.com/notifications/unsubscribe/AAdWB9tmtFMLWVEaaYe5KztoYbIAYwnQks5qHDjRgaJpZM4IqFFB>
> .
>



-- 
Best regards,
Daniël Bos


Your government is reading your email. Slow them down with encryption.

My public key: http://goo.gl/gms497 (4096 bit RSA, id EF2D5D91)
Fingerprint  : D8D0 9FBE F075 F709 7B52  2F73 326C 2123 EF2D 5D91

**Comment by yagebu** [comment]
I agree with @corani and I'm against removing any of the current links. Let's just make it scrollable. If someone decides to add a ton of custom links/queries, they can be expected to scroll.

> Move the error-idicator to a bubble next to the "Source"-menu-item or to it's own item below "Source" (as it was before, but hide it if there are no errors).

I would just move it to the top of the sidebar. The more noticeable the better IMHO

**Comment by adamgibbins** [comment]
Maybe move the queries and custom links under a sub-hover menu? Although those things are horrible from a touch-UI perspective.

I cannot think of any other clean solutions - I see no problem with scrolling so long as its obvious that you can scroll (as it'd be easy to position my window so that Options was clearly visible yet no sign there was something below).

**Comment by aumayr** [comment]
OK thanks for the suggestions. Removing something makes no sense, you are right. 

I'll try to do three things:
1. Move errors (have to try where is best). 
2. Make the scrollbar visible (Gmail-style)
3. Maybe tighten up the vertical spacing in the sidebar to allow for more items (just a little).

**Comment by yagebu** [comment]
Actually, I don't really use documents or notes so far, so I didn't know what the reports looked like, and I thought they contained some specific useful information. But they just show the Journal, so I'm actually for removing them.

Also, the "Net Worth" report can (and should) be removed. It's quite useless, all the data is on the balance sheet already.

**Comment by adamgibbins** [comment]
Could maybe add the option to turn off certain functionality? I too do not use notes, or events - but do use documents, so I'd be happy to not see those in the menu. Clearly a bit of a hack though, and only works until people have too many custom items.

**Comment by aumayr** [comment]
@adamgibbins In PR #311 I removed both Notes and Documents, but the option to add them back already exists: custom sidebar links!

@yagebu Any ideas of how to make the Net Worth report better/more useful? (Generally: In the beginning I just copied over all the views from `bean-web`, that's why Notes and Documents, etc. are still there in Fava.)

**Comment by aumayr** [comment]
PR #311 implements the changes described above. I'm pretty happy with them. 

@adamgibbins As creator of this issue: What do you think about these changes? Do they work for you?

**Comment by adamgibbins** [comment]
@aumayr yup, all the proposed in https://github.com/aumayr/fava/issues/308#issuecomment-222978589 sounds good to me + removing the redundant sidebar links.

**Comment by yagebu** [comment]
I don't think we need to make the Net Worth report anymore useful. Improvements should rather be directed at the holdings page and the balance sheet IMHO.

**Comment by aumayr** [comment]
@adamgibbins I will close this issue, as I merged PR #311
