### ISSUE TITLE
fava needs better responsive design

### ISSUE THREAD

**Issue by xentac** [aumayr/fava#309]
This is a follow-up to my comment on https://github.com/aumayr/fava/issues/39 and to tell everyone that I'm starting to think about this.

My response to the writing of (S)CSS by hand is having to solve the same problem, in a less general way, each time.  I prefer frameworks because people who have had to deal with these sorts of problems before have solved them more generally so the next time you think, "oh man, it'd be really cool if I could just ...", they probably already have a solution that fits within the framework.

I'll evaluate both cases though.  I don't really like the idea of having to tweak the layout every time there's a new screen/form factor/etc.

**Comment by xentac** [comment]
(Why do I have no idea how to use this interface? Can someone please assign this to me?)

A few things I've noticed just poking around:

1. The nav bar takes up too much space on a small screen.  That will need to be hideable.
2. Tables will need to be able to tell how many columns they have in them so that they can intelligently know when to switch from 50% width to 100%.  Right now if you have too many columns (like two currencies, plus other) it will usually extend outside the 50% size allotted.  This isn't cool.
3. Top bar extends to a funny length regardless of total width
4. Graphs don't always extend the right distance, but sometimes they do.

**Comment by aumayr** [comment]
> I'll evaluate both cases though. I don't really like the idea of having to tweak the layout every time there's a new screen/form factor/etc.

Please don't let you discourage from the "against-frameworks"-comment I made in #39 - you can introduce one if you like and it fits your needs for fixing this. 

> Why do I have no idea how to use this interface? Can someone please assign this to me?

Strangely I can't assign you as well :-/

**Comment by aumayr** [comment]
@xentac For which devices/browsers/sizes are you looking to optimize/implement the responsive design?

**Comment by xentac** [comment]
My plan was to work through the Responsive resolutions offered by the chrome inspect window.  The smallest is 320x508.

My guess is the assignee has to be someone who owns/admins the project.  I wouldn't worry too much about it.  This isn't me trying to get admin access to this project or anything ;)

**Comment by xentac** [comment]
Please consider https://github.com/aumayr/fava/pull/321 as my first attempt.

**Comment by aumayr** [comment]
Will close this, as #321 was merged (thanks @xentac!).
