### ISSUE TITLE
export to excel don't work 

### ISSUE THREAD

**Issue by pfrancois** [aumayr/fava#316]
if in the the query tab i try to export to other than csv, i have an error 500.
pleqse find the error in the case i try to export to excel

> [I 160604 22:37:26 handlers:132] Browser Connected: http://localhost:5000/beancount/query/?time=2016&query_string=balance+from+year+%3D+2014
> INFO:livereload:Browser Connected: http://localhost:5000/beancount/query/?time=2016&query_string=balance+from+year+%3D+2014
> ERROR:fava.application:Exception on /beancount/query/ [GET]
> Traceback (most recent call last):
>   File "/usr/lib/python3.4/site-packages/flask/app.py", line 1817, in wsgi_app
>     response = self.full_dispatch_request()
>   File "/usr/lib/python3.4/site-packages/flask/app.py", line 1477, in full_dispatch_request
>     rv = self.handle_user_exception(e)
>   File "/usr/lib/python3.4/site-packages/flask/app.py", line 1381, in handle_user_exception
>     reraise(exc_type, exc_value, tb)
>   File "/usr/lib/python3.4/site-packages/flask/_compat.py", line 33, in reraise
>     raise value
>   File "/usr/lib/python3.4/site-packages/flask/app.py", line 1475, in full_dispatch_request
>     rv = self.dispatch_request()
>   File "/usr/lib/python3.4/site-packages/flask/app.py", line 1461, in dispatch_request
>     return self.view_functions[rule.endpoint](**req.view_args)
>   File "/usr/lib/python3.4/site-packages/fava/application.py", line 191, in query
>     if not config['HAVE_EXCEL']:
> TypeError: 'module' object is not subscriptable
> [E 160604 22:37:35 wsgi:355] 500 GET /beancount/query/?result_format=xls&query_string=balances+from+year+%3D+2014&time=2016 (::1) 425.78ms
> ERROR:tornado.access:500 GET /beancount/query/?result_format=xls&query_string=balances+from+year+%3D+2014&time=2016 (::1) 425.78ms
> ERROR:fava.application:Exception on /favicon.ico [GET]
> Traceback (most recent call last):
>   File "/usr/lib/python3.4/site-packages/flask/app.py", line 1817, in wsgi_app
>     response = self.full_dispatch_request()
>   File "/usr/lib/python3.4/site-packages/flask/app.py", line 1477, in full_dispatch_request
>     rv = self.handle_user_exception(e)
>   File "/usr/lib/python3.4/site-packages/flask/app.py", line 1381, in handle_user_exception
>     reraise(exc_type, exc_value, tb)
>   File "/usr/lib/python3.4/site-packages/flask/_compat.py", line 33, in reraise
>     raise value
>   File "/usr/lib/python3.4/site-packages/flask/app.py", line 1473, in full_dispatch_request
>     rv = self.preprocess_request()
>   File "/usr/lib/python3.4/site-packages/flask/app.py", line 1660, in preprocess_request
>     func(request.endpoint, request.view_args)
>   File "/usr/lib/python3.4/site-packages/fava/application.py", line 346, in pull_beancount_file
>     g.beancount_file_slug = values.pop('bfile', None)
> AttributeError: 'NoneType' object has no attribute 'pop'
> [E 160604 22:37:35 wsgi:355] 500 GET /favicon.ico (::1) 5.48ms
> ERROR:tornado.access:500 GET /favicon.ico (::1) 5.48ms`

**Comment by corani** [comment]
Have you updated to the latest version? I can't find the indicated error on the latest master.

**Comment by yagebu** [comment]
This was fixed in 92299346.
