### ISSUE TITLE
Pad amount not shown in journals

### ISSUE THREAD

**Issue by xiaoruoruo** [aumayr/fava#319]
When there is a non-empty Pad transaction, the amount is not shown in the journals.

Test journal:

```
option "operating_currency" "USD"

2016-01-01 open Equity:Opening-Balances
2016-01-01 open Assets:Cash

2016-01-01 pad Assets:Cash Equity:Opening-Balances
2016-06-05 balance Assets:Cash 100 USD
```

![pad](https://cloud.githubusercontent.com/assets/452520/15807864/3dec75a8-2b1d-11e6-824c-a293359a4512.png)

**Comment by corani** [comment]
What you're looking for is the `padding`, not the `pad`. Confusing, I
know...

I believe it'll show when you select the "other" transactions (`x`)

**Comment by xiaoruoruo** [comment]
Indeed, turning on 'X' gets me what I wanted. Thanks.
