### ISSUE TITLE
Keyboard shortcuts: Some not working

### ISSUE THREAD

**Issue by jdrueke** [aumayr/fava#324]
Using Chrome version 50 on Ubuntu 15.10, several of the keyboard shortcuts not working.  Looking at the "Keyboard shortcuts" screen, those categorized as "General" through "Entry filters:filter by account" work.  The remainder, from "filter by payee" through "execute query" do not.

Pressing "m" flashes metadata briefly, but it does not persist.

Similar results from Firefox 46 on Windows 8.3

Thanks.

**Comment by aumayr** [comment]
@jdrueke Thanks for reporting this! 

Keyboard shortcuts should be fixed now (if you run from `master`). Can you test if they work for you?

**Comment by jdrueke** [comment]
I did a fresh install from https://github.com/aumayr/fava.git.

Now, none of the keyboard shortcuts work.  Also, the "Open, Close, 
Transaction, ...) buttons are now not working for me.

**Comment by aumayr** [comment]
@jdrueke Did you rebuild the js/css (`make build-js`)?

**Comment by jdrueke** [comment]
Here's my install process:

cd
sudo rm -rf fava
git clone https://github.com/aumayr/fava.git
cd fava
make build-js
sudo pip3 install --editable .

I just repeated it with the same result. Am I missing something?  Thanks.

**Comment by yagebu** [comment]
Does the `make build-js` show any errors? Could you also check the Javascript console in your browser to see if the Javascript code is loaded at all?

**Comment by jdrueke** [comment]
Javascript is loaded in both browsers, running under Ubuntu 15.10.  Here 
are messages:

make build-js says:
   npm WARN deprecated cross-spawn-async@2.2.4: cross-spawn no longer 
requires a build toolchain, use it instead!
   npm WARN prefer global node-gyp@3.3.1 should be installed with -g
   npm WARN optional Skipping failed optional dependency /chokidar/fsevents:
   npm WARN notsup Not compatible with your operating system or 
architecture: fsevents@1.0.12

sudo pip3 install --editable . says:
   warning: no files found matching 'CHANGES.md'
   warning: no files found matching 'RELEASENOTES.md'
   warning: no previously-included files matching '*' found under 
directory 'fava/static/javascript'
   warning: no previously-included files matching '*' found under 
directory 'fava/static/sass'
   warning: no previously-included files matching '*' found under 
directory 'fava/static/node_modules'
   warning: no previously-included files found matching 
'fava/static/package.json'
   warning: no previously-included files found matching 
'fava/static/webpack.config.js'
   warning: no previously-included files matching '*.pyc' found anywhere 
in distribution
   warning: no previously-included files matching '.gitignore' found 
anywhere in distribution
   warning: no previously-included files matching '*.orig' found 
anywhere in distribution

chromium 50.0 console says:
app.js:24677 Uncaught TypeError: this.input.setAttribute is not a function_
   @ app.js:24677(anonymous function)
   @ app.js:24641jQuery.extend.each
   @ app.js:477jQuery.fn.jQuery.each
   @ app.js:249initFilters
   @ app.js:24623(anonymous function)
   @ app.js:67fire
   @ app.js:3299self.fireWith
   @ app.js:3429jQuery.extend.ready
   @ app.js:3648completed
   @ app.js:3664

firefox 47.0 console says:
   mutating the [[Prototype]] of an object will cause your code to run 
very slowly; instead create the object with the correct initial 
[[Prototype]] value using Object.create app.js:23917:50
   TypeError: this.input.setAttribute is not a function

Thanks very much for your attention to this.

**Comment by yagebu** [comment]
I've moved a lot of the Javascript code around today. This broke some of it apparently, but it should be unrelated to this issue. Can you try this commit: https://github.com/aumayr/fava/commit/1b781c12670d291b5992365ca90c361a9686b49c

**Comment by jdrueke** [comment]
I reinstalled with git clone from Master.  All the keyboard shortcuts 
now work.  Great!

Possibly related is that the closing x in the filter lists (Time, Tag, 
etc.) no longer work.  The only way I can find to cancel a search is to 
use backspace or delete.

**Comment by yagebu** [comment]
> Possibly related is that the closing x in the filter lists (Time, Tag,
etc.) no longer work.  The only way I can find to cancel a search is to
use backspace or delete.

Missed that one, thank you!
