### ISSUE TITLE
hound integration

### ISSUE THREAD

**Issue by yegle** [aumayr/fava#328]
It looks like Hound is a good tool to do automatic code style check for PRs.

https://github.com/integrations/hound

**Comment by aumayr** [comment]
We already use `flake8` (as does https://houndci.com/configuration#python) in connection with `tox` and the TravisCI-integration. 

So whenever a commit is pushed to this repo, `flake8` is automatically run and errors get reported.

**Comment by yegle** [comment]
It still makes sense to use hound to lint check the Javascript code.

**Comment by yagebu** [comment]
We should be linting our JS code, but it should be a Make target anyway, so I don't really see a benefit in using their service.

**Comment by yagebu** [comment]
I've added the dependencies and config to run eslint using the airbnb config (which seems to be the closest thing to a good default that the Javascript community has come up with). It currently throws more than 2000 errors. Most of it is indentation though.

We already use some ES6 features (like `const`) so we should also integrate babel into our build process.
