### ISSUE TITLE
Missing a currency in a transaction and saving crashes fava

### ISSUE THREAD

**Issue by aumayr** [aumayr/fava#329]
This transaction crashes fava 0.3.0:

```
2016-06-10 * "" ""
  Expenses:Test       10.00
  Assets:Test
```

**Comment by aumayr** [comment]
OK there are different levels where this fails:

1. Serialization of an inventory in fava did assume that a currency is a string. But if it is missing, beancount returns a `beancount.core.number.MISSING` object. Added `str(...)` to the inventory serialization in d96936a to work around this, but it is not very "clean" IMHO. 
2. beancount fails in iterating over it's `DisplayContext`-object (used in the Options view in fava):

![screenshot](https://cloud.githubusercontent.com/assets/5135450/15958432/ecd3461a-2ef5-11e6-8f16-e8be9b4315a1.png)

@blais Is leaving out the currency in a transaction supported in beancount? Shouldn't that raise an error? If not: Is 2. (screenshot above) a bug in beancount?

**Comment by blais** [comment]
Leaving out the currency should raise an error
What's the input?

**Comment by aumayr** [comment]
@blais A transaction like this one:

```
2016-06-10 * "" ""
  Expenses:Test       10.00
  Assets:Test
```

**Comment by blais** [comment]
This should fail; it's a bug that it doesn't.
The issue is caused by recent changes to the parser merged from the booking
branch, changes made to afford a much more liberal interpolation.
I'll fix this over the weekend, this should raise an error.

**Comment by aumayr** [comment]
OK, thanks for looking into it!

**Comment by blais** [comment]
I added a check.

**Comment by aumayr** [comment]
Thanks!
