### ISSUE TITLE
Replace ace with codemirror

### ISSUE THREAD

**Issue by yagebu** [aumayr/fava#330]
Ever since moving our Javascript compilation to webpack, I've hated working with the editor component. The fact that it still works is actually somewhat surprising to me. It doesn't work well with modern ways of building JS (there's even a different project "brace" that basically does some search/replace on ace's code to make it suitable with browserify/webpack). The documentation of ace is (even for Javascript) quite terrible. The only way to extend our code for it seems to be by copy-pasting code for some other modes, adjusting it and hoping it will work.

Having such an import part of Fava in a (for me at least) state that can't see any proper maintenance is a bad idea IMHO. Codemirror can do everything that ace can as far as I can see and has the following benefits (and much more probably):

- Has good documentation.
- Can work with textarea.
- Works with webpack.

I've done some work to switch the query editor to codemirror (will submit a PR shortly), and how easy this was (thanks to good documentation) has convinced me that this change is a good idea. Any work on the ace editor has always been hours of trial and error...

**Comment by aumayr** [comment]
Will the completions (Account names, currencies, etc.) work with CodeMirror?

**Comment by corani** [comment]
I can think of the following features Codemirror needs to support:

- Context sensitive completions? (Something I've been working on, so in places where beancount expects an Account, it'll only show completions for Accounts)
- Template/Snippet completions would also be nice, I've been trying to get that to work as well in Ace (which I agree is a pain in the behind)
- Embedded languages (for highlighting of SQL code in `query` directives)

**Comment by yagebu** [comment]
> Will the completions (Account names, currencies, etc.) work with CodeMirror?

The code has to be adjusted of course but then it's possible (and easier) to do completions with CodeMirror.

> Context sensitive completions (Something I've been working on, so in places where beancount expects an Account, it'll only show completions for Accounts)

>Template/Snippet completions would also be nice, I've been trying to get that to work as well in Ace (which I agree is a pain in the behind)

Should be much simpler than with ace because everything is well-documented. (https://codemirror.net/doc/manual.html#addon_show-hint for example)

**Comment by yagebu** [comment]
I've had a long train journey yesterday (and luckily saved CodeMirror's documentation offline) so I did some of the work towards this in #331. It's integrated and supports the syntax. The lexer is already closer to beancount's than the one we had.

Mainly the completion is missing now (and some smaller things like the print margin), but so far everything has been a joy to implement.
