### ISSUE TITLE
Add Docker images

### ISSUE THREAD

**Issue by aumayr** [aumayr/fava#332]
(This is the successor to #314)

@yegle has made a Docker image for fava: https://hub.docker.com/r/yegle/fava/

@xentac already provided example-files how to use OAuth with nginx: 

> https://github.com/xentac/beancount-oauth2
> 
> Here is a skeleton config showing what I had to do.  It doesn't support the url limiting.  To do that, you need to change the nginx config like they say here: https://github.com/bitly/oauth2_proxy/#configuring-for-use-with-the-nginx-auth_request-directive

I propose the following:

- Add two Dockerfiles/images to the `contrib/docker`-folder: One with the latest stable version of fava, and one to build fava from source
- Add configuration (via env-variables) to enable/disable OAuth

Unfortunately, I do not have any experience with Docker, so any contributions are welcome. 

@yegle Can we use your images? Are you interested in this?

**Comment by xentac** [comment]
I have a Dockerfile that clones beancount and fava, builds them, and installs the vim module and a few other things.  I use it as the base for my hosted solution and to enter all my transactions.

I wouldn't call it particularly awesome, but if you wanted to go that route, I'd be willing to contribute that also.  It's not exactly appropriate for an entirely static hosted solution, yegle's image is better for that.

**Comment by aumayr** [comment]
Sounds good! Maybe wait with any work until @yegle comments as well. 

As said, I think it would be awesome to have two images: One for the latest stable release, and one that builds from source (as yegle's one does).

**Comment by yegle** [comment]
Sure, feel free to use it. https://github.com/yegle/fava-docker it's licensed under MIT.

Since docker images are using the user's ID as namespace (so my fava image would be yegle/fava), @aumayr do you want to register a separate account to host the "official“ images that are built from this github repo?

As an alternative I can also modify my docker settings to use the Dockerfile in this repo to build the image.

**Comment by aumayr** [comment]
I created https://hub.docker.com/r/fava/fava/ as a namespace. Can I add you @yegle as a team member to push the images? 

Is anyone else interested in docker-hub-team-membership?

**Comment by yagebu** [comment]
Is this going anywhere?

**Comment by adamgibbins** [comment]
I'd be happy to take this on if nobody else is interested. I use @yegle's on a regular basis, if there's interest in making that official it'd be nice to just shift it over to the fava namespace instead of duplicating, if @yegle is happy with that.

**Comment by yegle** [comment]
I'm all fine with the changes.

**Comment by yagebu** [comment]
The dockerfile only installs Fava and doesn't really do anything that running Fava from the command line can't do, right? I've not used Docker before so I might not be aware of some of the advantages of it in this use-case, but it seems to me that it just adds a layer of complexity. How is it easier than running `pip3 install beancount-fava`?

**Comment by aumayr** [comment]
@adamgibbins Can I add you to https://hub.docker.com/r/fava/fava/ as a team member so that you can push the images?

**Comment by adamgibbins** [comment]
@aumayr Sure

**Comment by aumayr** [comment]
@adamgibbins and @yegle I have added you to https://hub.docker.com/u/fava => Feel free to push images, etc.

@xentac Can I add you as well?

It would be awesome if - when you push a new image there - you could add the Dockerfile/docker-compose.yml (and other resources) to the `/contrib` directory via a PR. 

As for now I will close this issue. Please reopen if you have questions/something to discuss.

**Comment by xentac** [comment]
Feel free to add me as well.  I don't know how much I'll be contributing, but I wouldn't mind having access.

I'm xentac on dockerhub.

**Comment by aumayr** [comment]
@xentac Can you share details about your setup with Docker+Fava+OAuth (https://github.com/beancount/fava/pull/504#issuecomment-294576296)? How did you build it and where do you host it?

**Comment by xentac** [comment]
You forgot +letsencrypt, which is how I get my SSL certs ;)

**Comment by xentac** [comment]
I'll write a README for the docker contrib directory that outlines something like how I set this up.

**Comment by xentac** [comment]
Just to prove that I haven't forgotten, here is where I've started writing the doc

https://github.com/xentac/fava/tree/dockerdocs/contrib/docker
