### ISSUE TITLE
Remove github references in fava/static/package.json

### ISSUE THREAD

**Issue by xentac** [aumayr/fava#340]
When I build fava with docker, it complains at the make build-js step because I don't have my github account ssh keys available.

Can you remove the github: from package.json?

https://github.com/aumayr/fava/blob/master/fava/static/package.json#L37

I've been doing it for a while in my own Dockerfile and it just seems to clone from the https url instead of the ssh one.

**Comment by aumayr** [comment]
Sure!

For reference: https://docs.npmjs.com/files/package.json#github-urls
