### ISSUE TITLE
Order listings by column

### ISSUE THREAD

**Issue by jmgilman** [aumayr/fava#343]
I've scoured the documentation and cannot find if this feature is supported or not, so I apologize if I missed it.

Basically, in the balance sheets, journals, etc. provide a method for ordering by a given column (based on the type). For instance, in particular being able to swap whether the default date ordering is ascending or descending. For other columns, order by alphabetical or numerical depending on the type. 

Ideally this would be integrated into the column header such that clicking it would change the order.

**Comment by aumayr** [comment]
This is currently not supported/implemented, so you haven't missed it ;-)

For basic tables (Statistics, Options, etc.) this is already implemented Client-side with JavaScript, as these are real `<table>`s. Advanced tables like Balance Sheet, Journal, etc. are not real `<table>`s, so this has to be done Server-side in Python.

I will keep this issue open as an `enhancement` and will have a look into it as how hard/easy it is to implement this. 

Thanks for reporting!

**Comment by jmgilman** [comment]
Thanks!

I've been browsing the source code a bit but haven't yet put all the pieces together. If I get some more time in the coming weeks I will give my attempt to it and submit a pull request.

**Comment by aumayr** [comment]
Great! If you have any questions regarding the source code or other parts, feel free to open an issue!

**Comment by yagebu** [comment]
Even though we're not using `<table>`s, I think this can and should be done in Javascript. Reordering the Journal in Python would lead to all kinds of inconsistencies.
