### ISSUE TITLE
Account auto-complete missing accounts

### ISSUE THREAD

**Issue by xiaoruoruo** [aumayr/fava#349]
Starting with 
```
option "operating_currency" "USD"
2016-07-01 open Expenses:Food
2016-07-01 open Expenses:Food:Meat
```

Auto-complete cannot give Expenses:Food, see screenshot.

![issue](https://cloud.githubusercontent.com/assets/452520/17656561/3ec3f250-6270-11e6-9fa0-ad4ea6b58482.png)

**Comment by aumayr** [comment]
Thanks @xiaoruoruo for reporting this. Will look into it at the end of the week.

**Comment by aumayr** [comment]
@blais Is this scenario/account setup supported?

```javascript
option "operating_currency" "USD"
2016-07-01 open Expenses:Food
2016-07-01 open Expenses:Food:Meat
```

**Comment by yagebu** [comment]
That's supported yes. The reason why `Expenses:Food` doesn't show up is that we're only feeding leaf accounts to the completion. We could do better and list all those that have at least one entry.

**Comment by xiaoruoruo** [comment]
Seems still not completing all accounts? Compiled and reinstalled at d71ec60.
![screen shot 2016-08-24 at 22 09 54](https://cloud.githubusercontent.com/assets/452520/17957551/8233af06-6a47-11e6-81ee-a94f4a33fc0e.png)

**Comment by yagebu** [comment]
There was a small bug. Should work now.

**Comment by xiaoruoruo** [comment]
Thanks!
