### ISSUE TITLE
Option to serve on a different root

### ISSUE THREAD

**Issue by xiaoruoruo** [aumayr/fava#350]
The fava command has --host and --port, listening on http://host:port/. If I want to put it behind a reverse proxy, for example, listening on http://host/fava/ and forwarding to http://host:port/, fava loads static resources from http://host/static/.. instead of http://host/fava/static/..

Can fava add an option to serve on a different root (/fava) so that it could be used this way?

**Comment by aumayr** [comment]
Sounds like a reasonable enhancement. Will look into implementing this.
