### ISSUE TITLE
time-filter based accounts in balance sheet

### ISSUE THREAD

**Issue by happyalu** [aumayr/fava#357]
Is there a setting that allows me to do the following in the balance sheet and income view, given a time filter.

If 
(a) an account does not have any transactions in the specified period, AND
(b) the balance in the account is zero,
then do not display that account.

I believe this is what bean-web does by default.

**Comment by aumayr** [comment]
@happyalu No, the decision to show all accounts and not hiding them if there is no balance, was deliberate. Currently there is no setting for this, either.

**Comment by yagebu** [comment]
Don't the `show-accounts-with-zero-balance` and `show-accounts-with-zero-transactions` settings allow you to do this?
