### ISSUE TITLE
Add script to "scrape-test" the frontend

### ISSUE THREAD

**Issue by aumayr** [aumayr/fava#36]
@blais (on the Mailing list):

> One kind of test that is easily implemented and which has been really beneficial in avoiding total undetected breakage in bean-web is a generic "scrape everything and check for errors" automated test, like I do it:
> https://bitbucket.org/blais/beancount/src/c5252218c11b9f96c57e1423fb3f38314916149b/src/python/beancount/web/scrape.py?at=default&fileviewer=file-view-default
> 
> This just runs as part of my suite of unit tests and gives me a sense that changes to the core don't break the front-end. You may want to consider adding something like this to beancount-web.

**Comment by blais** [comment]
Glad it works.
Just curious: Why not just import it from Beancount itself?
If you'd like I remove the import of beancount.web.web, I can find a way to
isolate it so you could import the scraper directly instead of forking it.
Let me know,

**Comment by blais** [comment]
I isolated away the dependency to beancount.web.web in the scraping code.
If you'd like to just import it and reuse it, you can now do that.
https://bitbucket.org/blais/beancount/commits/0a17a0f0e00a445f64a7b66c37f9f6007073358e

**Comment by aumayr** [comment]
Thanks @blais! I will simplify the code and use your function instead.
