### ISSUE TITLE
Remove or fix the alternative theme.

### ISSUE THREAD

**Issue by yagebu** [aumayr/fava#363]
The alternative theme is quite broken currently and has been for ages. Broken not in the sense that it doesn't compile but rather that most pages just look like *crap*. As this has been the case for a few releases now, I doubt that anyone is using it.

It takes effort to keep it compiling when changes are made to the stylesheets, and I find it hard to justify that. Also, I don't like shipping crap, so I'm strongly for removing it.

Is anyone using it and willing to maintain it?

**Comment by aumayr** [comment]
As you have said, because it is _crap_ and no one complained so far, I guess no one is using it. 

So I'm all for removing it.
