### ISSUE TITLE
Scrolling when cursor is on a treemap chart does not work

### ISSUE THREAD

**Issue by aumayr** [aumayr/fava#372]
When the cursor is on a treemap chart, scrolling does not work. It looks like the scrolling-event is caught and prevented by the treemap chart. 

@yagebu Do you know why this is?

**Comment by yagebu** [comment]
This is the (currently) intended behaviour as you can use scroll to zoom into the treemaps. I'm open to removing this functionality if you find it annoying.

**Comment by aumayr** [comment]
Would be awesome if you remove this feature, as the treemap fills a very large area on my 13", and therefore scrolling is really cumbersome.
