### ISSUE TITLE
Move Fava to it's own Github Organization

### ISSUE THREAD

**Issue by aumayr** [aumayr/fava#383]
I intend to move Fava away from my personal Github account and into it's own Github Organization, as @yagebu does more and more of the work, and there are many contributers, so it seems the right thing to do. 

I personally have created two organizations already to claim the names until we have settled on how to call the organization:

- https://github.com/beancount (with https://github.com/beancount/fava as the repo)
- https://github.com/beancount-fava

The `fava`-organization (which would be perfect) already exists, but seems publicly inactive:

- https://github.com/fava

What do you think?

**Comment by aumayr** [comment]
@njm2112 I think you are the owner of the `fava`-Organization. As there is no public activity, do you use it privately? If not: Would you be willing to make the name available to us?

**Comment by aumayr** [comment]
@blais Are you interested in the `beancount`-Organization/name?

Would https://github.com/beancount/fava be acceptable to you?

**Comment by gour** [comment]
@aumayr Go for it!! It's nice to see more interest for Beancount & related tools...

**Comment by blais** [comment]
Urg... I don't use Git very much. Still secretely hoping Betamax wins over VHS, but, do I need to do something to get it?

**Comment by njm2112** [comment]
> @njm2112 I think you are the owner of the fava-Organization. As there is no public activity, do you use it privately? If not: Would you be willing to make the name available to us?

@aumayr: no, i'm not the owner; i might've forked the repo at some point but i have nothing to do with http://github.com/fava. sorry!

**Comment by gour** [comment]
@blais Ohh, I was not aware that you're using [Fossil](http://fossil-scm.org).  ;)

**Comment by aumayr** [comment]
@blais I already created the `beancount` organization, and will add you as a member. There is nothing else you have to do.

@blais @yagebu What do you think about https://github.com/beancount/fava? (eg. moving Fava to the `beancount` organization)

**Comment by blais** [comment]
No particular opinion on it.
I wouldn't mind having a one-way mirror from bitbucket to
github.com/beancount/beancount either.

**Comment by aumayr** [comment]
@blais I created https://github.com/beancount/beancount and added you as an Admin. Maybe you can use this tool to setup the one-way mirror: http://www.metallapan.se/bitsynchub/

**Comment by aumayr** [comment]
@njm2112 Oh, sorry! Thanks anyway for responding!

**Comment by blais** [comment]
Thanks Dominik!

**Comment by yagebu** [comment]
If Martin doesn't mind, I'm very happy about `beancount/fava` (although `fava/fava` would be even nicer, as it would give us the `fava.github.io` domain).

**Comment by aumayr** [comment]
OK it's settled then - we will move to `beancount/fava` 🙂

Before moving, I want to collect the things that have to be changed:

- [ ] https://aumayr.github.io/fava => https://beancount.github.io/fava
- [ ] Update scripts for pythonanywhere.com
- [ ] Help and docs
- [ ] Move over the repo (Can we also move over all issues, etc?)

**Comment by aumayr** [comment]
Will close this issue as it is now settled and will be tracked in #390
