### ISSUE TITLE
show-accounts-with-zero-balance logic reversed?

### ISSUE THREAD

**Issue by adamgibbins** [aumayr/fava#389]
I'm seeing some unexpected behaviour when setting `1990-01-01 custom "fava-option" "show-accounts-with-zero-balance" "false"`, when its false most of my accounts disappear (but not all, I can't workout why some stay) and all of my empty accounts appear on the balance sheet.  If I set it to true (i.e. the default) all of my not-empty accounts appear as well as some(all?) empty accounts.

**Comment by yagebu** [comment]
Ups, the boolean condition was indeed evaluating to exactly the opposite of what we wanted...

Thanks for the report!
