### ISSUE TITLE
At small resolutions, the expand button has disappeared

### ISSUE THREAD

**Issue by xentac** [aumayr/fava#391]
It looks like something changed in the CSS that caused the "#aside-button" that's defined within the aside to not be visible at all.  My guess is the style was updated such that overflow was hidden in some ways.

I did find that disabling overflow-y: auto on the aside element made the button visible again.

**Comment by yagebu** [comment]
Ah it seems mobile browsers just ignore parts of the web standards they don't like. Moving the button outside the aside seems to fix it (at least in the Chrome dev tools), so I'll do that.
