### ISSUE TITLE
Selectively hiding accounts in the account hierarchy

### ISSUE THREAD

**Issue by redstreet** [aumayr/fava#91]
This is a feature request, if it interests you: it would be useful to be optionally able to not display leaf accounts in the hierarchy in various situations:
- when there are zero transactions for a given account in the current context (period/filters)
- when the final balance is zero in the current context
- when the account has been closed (when you don't want to see a bunch of irrelevant accounts from the past)
- specific set of accounts listed in the config file

This would help reduce clutter, particularly for folks with detailed hierarchies and/or long histories.

**Comment by corani** [comment]
I don't think hiding specific accounts is a good idea (it messes up the totals) or hiding accounts with zero balance (it makes them difficult to find)

However, I can see the merit of hiding accounts with no transactions.

I believe accounts closed before the start-date or opened after the end-date of the current context are already hidden.

**Comment by redstreet** [comment]
> I don't think hiding specific accounts is a good idea (it messes up the totals) 

Good point. Perhaps an alternative is to allow for a config option in the .conf file where one can list accounts, either directly, or through a regexp that need to be shown collapsed by default? The idea is to allow better insight by reducing visual clutter for those with detailed hierarchies that are long and deep. For example, when I am analyzing investments, I'd rather not see a long list of accounts of what is owed to me. So I always end up collapsing a whole bunch of parents manually.

> or hiding accounts with zero balance (it makes them difficult to find)

Let me emphasize that that this would be an option in the .conf file. So the defaults wouldn't change from now, but will provide advanced users with the option to do so. As an example of the use case for this, see:
https://github.com/redstreet/beancount_plugins_redstreet/tree/master/zerosum

I believe these types of accounts are very useful (they certainly are for me!). I have a detailed hierarchy of these accounts to rapidly track down accounting errors. It would help if only the accounts with non-zero balances are displayed (again, optionally). Of course, any parent in the hierarchy necessary for a coherent display would be shown.

> I believe accounts closed before the start-date or opened after the end-date of the current context are already hidden.

True, this is helpful, and this proposal basically extends this idea.

**Comment by redstreet** [comment]
Cool, works nicely, thanks!

Would you consider adding options to hide accounts with zero transactions, and those with zero balances in the current context? Or is that too much of a pain?

**Comment by aumayr** [comment]
> Would you consider adding options to hide accounts with zero transactions, and those with zero balances in the current context? Or is that too much of a pain?

I think zero transactions should be the easier one, but zero balances sounds strange. What if there are transactions, but the account balance goes to zero? Would you like to hide it as well?

**Comment by redstreet** [comment]
> I think zero transactions should be the easier one, but zero balances sounds strange. What if there are transactions, but the account balance goes to zero? Would you like to hide it as well?

Yes, I think these would each be separate options ("hide-accounts-with-zero-transactions" and "hide-accounts-with-zero-balance"). The former is obviously helpful, but the latter is also helpful in several situations like:
- dormant (but not closed) Asset or Liability accounts (say bank or credit card). I (and I suspect many users) spend a lot of time without a time-context selected, and in these cases, it's helpful to reduce the clutter of these accounts
- for quickly being able to see only the accounts that affect the bottomline or the balance

**Comment by yagebu** [comment]
In my opinion closed accounts should not be shown by default (but can be with an option). Providing options to hide accounts with no transactions or with balance == 0 are also sensible suggestions (the first more so than the latter in my opinion).

**Comment by redstreet** [comment]
Thanks, these are very helpful!
#234 adds this to the documentation.
